import { Predicate } from "effect";
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../../src/integrations/polymarket/', import.meta.url);
const specs = Object.fromEntries(await Promise.all(['data','gamma','clob'].map(async name => [name, JSON.parse(await readFile(new URL(`specs/${name}.json`, import.meta.url), 'utf8'))])));
const selections = {
  data: Object.keys(specs.data.paths).map(path => [path.slice(4).replaceAll('-', '_').replaceAll('/', '_'), path]),
  gamma: [
    ['search','/public-search','q,events_status,limit_per_type,page,search_tags,search_profiles,events_tag'],
    ['events','/events/keyset','limit,after_cursor,order,ascending,closed,live,title_search,tag_id,tag_slug,series_id,slug,end_date_min,end_date_max,volume_min'],
    ['markets','/markets/keyset','limit,after_cursor,order,ascending,closed,slug,clob_token_ids,condition_ids,tag_id,volume_num_min,liquidity_num_min,end_date_min,end_date_max'],
    ['event','/events/{id}'], ['event_by_slug','/events/slug/{slug}'],
    ['market','/markets/{id}'], ['market_by_slug','/markets/slug/{slug}'],
    ['tags','/tags'], ['tag','/tags/{id}'], ['tag_by_slug','/tags/slug/{slug}'],
    ['event_tags','/events/{id}/tags'], ['market_tags','/markets/{id}/tags'],
    ['related_tags','/tags/{id}/related-tags/tags'],
    ['series','/series','limit,offset,slug,closed,recurrence,exclude_events'], ['series_detail','/series/{id}'],
    ['sports','/sports'], ['sports_market_types','/sports/market-types'], ['teams','/teams'],
    ['profile','/public-profile'],
  ],
  clob: [['book','/book'],['price','/price'],['midpoint','/midpoint'],['spread','/spread'],['last_trade_price','/last-trade-price'],['fee_rate','/fee-rate'],['tick_size','/tick-size'],['negative_risk','/neg-risk'],['clob_market','/clob-markets/{condition_id}'],['market_by_token','/markets-by-token/{token_id}'],['rewards','/rewards/markets/current'],['market_rewards','/rewards/markets/{condition_id}'],['server_time','/time']],
};
const origins = {data:'https://data-api.polymarket.com',gamma:'https://gamma-api.polymarket.com',clob:'https://clob.polymarket.com'};
const q = JSON.stringify;
const requiredUser = new Set(['activity','activity_combos','approvals','positions_combos','user_pnl','user_stats','user_volume','value']);
const enums = { time_period:['day','week','month','all'], sort_direction:['ASC','DESC'], side:['BUY','SELL'], filter_type:['CASH','TOKENS'] };
function deref(s, spec) { return s.$ref ? s.$ref.slice(2).split('/').reduce((v,k)=>v[k],spec) : s; }
function zod(s) {
  const type = Array.isArray(s.type) ? s.type.find(t=>t!=='null') : s.type;
  if(s.enum) return `z.enum(${q(s.enum)})`;
  if(type==='array') return `z.array(${zod(s.items)}).max(20)`;
  if(type==='boolean') return 'z.boolean()';
  if(type==='integer'||type==='number') return `z.number()${type==='integer'?'.int()':''}${s.minimum!==undefined?`.min(${s.minimum})`:''}${s.maximum!==undefined?`.max(${s.maximum})`:''}`;
  return `z.string().min(1).max(2000)${s.pattern?`.regex(new RegExp(${q(s.pattern)}))`:''}`;
}
const notices = 'Generated by scripts/polymarket/generate.mjs from the pinned official OpenAPI snapshots. Do not edit.';
let catalog = `// ${notices}\nimport { z } from "zod";\nimport { defineEndpoint } from "./endpoint";\nimport * as data from "./data.generated";\nimport * as gamma from "./gamma.generated";\nimport * as clob from "./clob.generated";\n\nexport const polymarketEndpoints = {\n`;
const manifest = [];
for (const [family, entries] of Object.entries(selections)) {
 const spec=specs[family], definitions=new Map();
 function model(s, mode) {
  if (s.$ref) {
   const name=s.$ref.split('/').at(-1);
   if(!definitions.has(name)) { definitions.set(name,null); const target=deref(s,spec);
    const required = family === 'gamma' ? { KeysetEventsResponse: ['events'], KeysetMarketsResponse: ['markets'], Event: ['id','title'], Market: ['id','question'] }[name] : undefined;
    const contract = required ? {...target, required: [...new Set([...(target.required||[]), ...required])]} : target;
    definitions.set(name,{type:model(contract,'type'),schema:model(contract,'schema')}); }
   return name;
  }
  if(s.nullable) return mode==='type'?`(${model({...s,nullable:false},mode)} | null)`:`Schema.NullOr(${model({...s,nullable:false},mode)})`;
  if(s.oneOf||s.anyOf) {const parts=(s.oneOf||s.anyOf).map(v=>model(v,mode));return mode==='type'?`(${parts.join(' | ')})`:`Schema.Union([${parts.join(', ')}])`;}
  if(Array.isArray(s.type)) {const parts=s.type.map(type=>model({...s,type},mode));return mode==='type'?`(${parts.join(' | ')})`:`Schema.Union([${parts.join(', ')}])`;}
  if(s.enum) return mode==='type'?s.enum.map(q).join(' | '):`Schema.Literals(${q(s.enum)})`;
  if(s.allOf) {const parts=s.allOf.map(v=>model(v,mode));if(parts.length===1)return parts[0];throw Error('Unsupported allOf');}
  switch(s.type) {
   case 'null': return mode==='type'?'null':'Schema.Null';
   case 'string': return mode==='type'?'string':s.pattern?`Schema.String.check(Schema.isPattern(new RegExp(${q(s.pattern)})))`:'Schema.String';
   case 'number': case 'integer': return mode==='type'?'number':'Schema.Number';
   case 'boolean': return mode==='type'?'boolean':'Schema.Boolean';
   case 'array': return mode==='type'?`ReadonlyArray<${model(s.items,mode)}>`:`Schema.Array(${model(s.items,mode)})`;
   case 'object': {
    if(!s.properties) return mode==='type'?`Readonly<Record<string, ${s.additionalProperties && Predicate.isRecord(s.additionalProperties)?model(s.additionalProperties,mode):'Schema.Json'}>>`:`Schema.Record(Schema.String, ${s.additionalProperties && Predicate.isRecord(s.additionalProperties)?model(s.additionalProperties,mode):'Schema.Json'})`;
    const fields=Object.entries(s.properties).map(([k,v])=>{const optional=!s.required?.includes(k);const value=model(v,mode);return mode==='type'?`readonly ${q(k)}${optional?'?':''}: ${value};`:`${q(k)}: ${optional?`Schema.optionalKey(${value})`:value},`;});
    return mode==='type'?`{\n${fields.join('\n')}\n}`:`Schema.Struct({\n${fields.join('\n')}\n})`;
   }
   default: if(Object.keys(s).some(k=>!['description','example','title'].includes(k)))throw Error(`Unsupported schema ${q(s)}`);return 'Schema.Json';
  }
 }
 for(const [name,path,filter] of entries) {
  const op=spec.paths[path].get;
  if(op.security?.length) throw Error(`Authenticated operation ${name}`);
  let response=deref(op.responses['200'],spec).content['application/json'].schema;
  const decimal = {type:'string', pattern:'^(?:0|1)(?:\\.[0-9]+)?$'};
  if(family==='clob' && path==='/price') response={type:'object',required:['price'],properties:{price:{oneOf:[{type:'number'},decimal]}}};
  if(family==='clob' && path==='/midpoint') response={oneOf:[{type:'object',required:['mid'],properties:{mid:decimal}},{type:'object',required:['mid_price'],properties:{mid_price:decimal}}]};
  const responseName=name+'Response';
  definitions.set(responseName,{type:model(response,'type'),schema:model(response,'schema')});
  const parameters=(op.parameters||[]).map(p=>deref(p,spec)).filter(p=>!filter||filter.split(',').includes(p.name));
  const fields=parameters.map(p=>{
   const k=p.name;
   let code=zod(p.schema);
   if(['user','address'].includes(k))code='z.string().regex(/^0x[a-fA-F0-9]{40}$/)';
   if(k==='token_id')code='z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/)';
   if(k==='condition_id'||k==='question_id')code='z.string().regex(/^0x[a-fA-F0-9]{64}$/)';
   if(k==='condition')code='z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/)';
   if(family==='data'&&k==='event_id')code='z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/)';
   if(['id'].includes(k)&&p.in==='path')code='z.string().regex(/^[0-9]+$/)';
   if(k==='slug'&&p.in==='path')code='z.string().min(1).max(300).regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/)';
   if(k==='cursor'||k==='after_cursor'||k==='next_cursor')code='z.string().min(1).max(16384)';
   if(k==='limit'||k==='limit_per_type')code=`z.number().int().min(1).max(${Math.min(p.schema.maximum||100,100)})`;
   if(['start','end','as_of','updated_after','updated_before'].includes(k))code=`z.number().int().min(${name==='prices_history'?1:0})`;
   if(family==='data'&&enums[k])code=`z.enum(${q(enums[k])})`;
   if(name==='positions'&&k==='status')code='z.enum(["OPEN","REDEEMABLE","REDEEMABLE_LOST","MERGEABLE","CLOSED"])';
   if(name==='positions'&&k==='sort_by')code='z.enum(["CURRENT_VALUE","PRICE","TOKENS","UNREALIZED_PNL","REALIZED_PNL","TOTAL_PNL","TIMESTAMP"])';
   if(name==='activity'&&k==='sort_by')code='z.literal("TIMESTAMP")';
   if(name==='leaderboard'&&k==='sort_by')code='z.enum(["PNL","VOLUME"])';
   if(name==='prices_history'&&k==='interval')code='z.enum(["max","all","1m","1w","1d","6h","1h"])';
   if(name==='prices_history'&&k==='bucket_seconds')code='z.number().int().min(60).max(86400)';
   if(name==='user_pnl'&&k==='interval')code='z.enum(["max","all","1m","1w","1d","12h","6h"])';
   if(name==='user_pnl'&&k==='fidelity')code='z.enum(["1d","18h","12h","3h","1h"])';
   if(name==='builders_volume'&&k==='interval')code='z.enum(["day","week","month","all"])';
   const required=p.required||k==='token_id'||requiredUser.has(name)&&k==='user'||name==='holders'&&k==='condition'||name==='live_volume'&&k==='event_id';
   if(!required)code+='.optional()';
   if(p.description)code+=`.describe(${q(p.description.slice(0,900))})`;
   return `${q(k)}: ${code},`;
  });
  const pagination=parameters.some(p=>p.name==='cursor')?'cursor':parameters.some(p=>p.name==='after_cursor')?'after_cursor':parameters.some(p=>p.name==='next_cursor')?'next_cursor':parameters.some(p=>p.name==='page')?'page':parameters.some(p=>p.name==='offset')?'offset':undefined;
  const description=(op.summary||name.replaceAll('_',' '))+'. '+(op.description||'').slice(0,900);
  catalog+=`${name}: defineEndpoint({ name: ${q(name)}, origin: ${q(origins[family])}, path: ${q(path)}, description: ${q(description)}, input: z.strictObject({\n${fields.join('\n')}\n}), response: ${family}.${responseName}, pagination: ${q(pagination)||'undefined'} }),\n`;
  manifest.push({name,family,path,pagination});
 }
 const output=`// ${notices}\nimport { Schema } from "effect";\n\n`+[...definitions].map(([name,{type,schema}])=>`export type ${name} = ${type};\nexport const ${name}: Schema.Codec<${name}> = Schema.suspend(() => ${schema});\n`).join('\n');
 await writeFile(new URL(`${family}.generated.ts`,root),output);
}
catalog+='} ;\nexport type PolymarketEndpointName = keyof typeof polymarketEndpoints;\nexport const polymarketEndpointNames = Object.keys(polymarketEndpoints).filter((name): name is PolymarketEndpointName => name in polymarketEndpoints);\n';
await writeFile(new URL('catalog.generated.ts',root),catalog);
await writeFile(new URL('endpoints.json',import.meta.url),JSON.stringify(manifest,null,2)+'\n');
console.log(`Generated ${manifest.length} public Polymarket endpoints.`);
