import type { ReactNode } from "react";
import { AbsoluteFill, Html5Audio, staticFile, useCurrentFrame } from "remotion";
import { Bento } from "./Bento";
import { Chat } from "./Chat";
import "./fonts";
import { Headline } from "./Headline";
import { frames } from "./motion";
import { Outro } from "./Outro";
import "./styles.css";
import { headlines } from "./timeline";

/** Headlines are mounted only around their own time so off-screen words never render. */
function Timed({ from, to, children }: { from: number; to: number; children: ReactNode }) {
  const frame = useCurrentFrame();
  return frame >= frames(from) && frame < frames(to) ? children : null;
}

const column = { left: 60, top: 0, bottom: 0, width: 330, display: "flex", flexDirection: "column", justifyContent: "center" } as const;

export function Explainer() {
  return (
    <AbsoluteFill className="pecu-theme film">
      {/* Generated by scripts/sound.ts from the same timeline. */}
      <Html5Audio src={staticFile("soundtrack.wav")} />
      <div className="canvas">
        <Chat />
        <Timed from={headlines.intro.enter} to={headlines.intro.exit + 1}>
          <Headline copy={headlines.intro} size={38} align="center" style={{ left: 0, right: 0, top: 402 }} />
        </Timed>
        {(["ask", "swap", "stocks", "data"] as const).map((key) => (
          <Timed key={key} from={headlines[key].enter} to={headlines[key].exit + 1}>
            <Headline copy={headlines[key]} size={44} style={column} />
          </Timed>
        ))}
        <Bento />
        <Timed from={headlines.more.enter} to={headlines.more.exit + 1}>
          <Headline copy={headlines.more} size={44} style={{ left: 60, top: 44 }} />
        </Timed>
        <Outro />
      </div>
    </AbsoluteFill>
  );
}
