/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TapPublicIdRouteImport } from './routes/tap/$publicId'
import { Route as AppVoiceRouteImport } from './routes/_app/voice'
import { Route as AppSitesRouteImport } from './routes/_app/sites'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMindRouteImport } from './routes/_app/mind'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppHiveRouteImport } from './routes/_app/hive'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppBeeRouteImport } from './routes/_app/bee'
import { Route as AppHealthIndexRouteImport } from './routes/_app/health/index'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppHealthWaterRouteImport } from './routes/_app/health/water'
import { Route as AppHealthTapActionsRouteImport } from './routes/_app/health/tap-actions'
import { Route as AppGoalsGoalIdRouteImport } from './routes/_app/goals/$goalId'
import { Route as AppHealthJournalIndexRouteImport } from './routes/_app/health/journal/index'
import { Route as AppHealthJournalEntryIdRouteImport } from './routes/_app/health/journal/$entryId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapPublicIdRoute = TapPublicIdRouteImport.update({
  id: '/tap/$publicId',
  path: '/tap/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMindRoute = AppMindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHiveRoute = AppHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppBeeRoute = AppBeeRouteImport.update({
  id: '/bee',
  path: '/bee',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthIndexRoute = AppHealthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHealthRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthWaterRoute = AppHealthWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => AppHealthRoute,
} as any)
const AppHealthTapActionsRoute = AppHealthTapActionsRouteImport.update({
  id: '/tap-actions',
  path: '/tap-actions',
  getParentRoute: () => AppHealthRoute,
} as any)
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthJournalIndexRoute = AppHealthJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => AppHealthRoute,
} as any)
const AppHealthJournalEntryIdRoute = AppHealthJournalEntryIdRouteImport.update({
  id: '/journal/$entryId',
  path: '/journal/$entryId',
  getParentRoute: () => AppHealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bee': typeof AppBeeRoute
  '/health': typeof AppHealthRouteWithChildren
  '/hive': typeof AppHiveRoute
  '/jobs': typeof AppJobsRoute
  '/mind': typeof AppMindRoute
  '/settings': typeof AppSettingsRoute
  '/sites': typeof AppSitesRoute
  '/voice': typeof AppVoiceRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/health/tap-actions': typeof AppHealthTapActionsRoute
  '/health/water': typeof AppHealthWaterRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/health/': typeof AppHealthIndexRoute
  '/health/journal/$entryId': typeof AppHealthJournalEntryIdRoute
  '/health/journal/': typeof AppHealthJournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bee': typeof AppBeeRoute
  '/hive': typeof AppHiveRoute
  '/jobs': typeof AppJobsRoute
  '/mind': typeof AppMindRoute
  '/settings': typeof AppSettingsRoute
  '/sites': typeof AppSitesRoute
  '/voice': typeof AppVoiceRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/health/tap-actions': typeof AppHealthTapActionsRoute
  '/health/water': typeof AppHealthWaterRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/goals': typeof AppGoalsIndexRoute
  '/health': typeof AppHealthIndexRoute
  '/health/journal/$entryId': typeof AppHealthJournalEntryIdRoute
  '/health/journal': typeof AppHealthJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bee': typeof AppBeeRoute
  '/_app/health': typeof AppHealthRouteWithChildren
  '/_app/hive': typeof AppHiveRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/mind': typeof AppMindRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/voice': typeof AppVoiceRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/_app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/_app/health/tap-actions': typeof AppHealthTapActionsRoute
  '/_app/health/water': typeof AppHealthWaterRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/health/': typeof AppHealthIndexRoute
  '/_app/health/journal/$entryId': typeof AppHealthJournalEntryIdRoute
  '/_app/health/journal/': typeof AppHealthJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bee'
    | '/health'
    | '/hive'
    | '/jobs'
    | '/mind'
    | '/settings'
    | '/sites'
    | '/voice'
    | '/tap/$publicId'
    | '/goals/$goalId'
    | '/health/tap-actions'
    | '/health/water'
    | '/projects/$projectId'
    | '/goals/'
    | '/health/'
    | '/health/journal/$entryId'
    | '/health/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bee'
    | '/hive'
    | '/jobs'
    | '/mind'
    | '/settings'
    | '/sites'
    | '/voice'
    | '/tap/$publicId'
    | '/goals/$goalId'
    | '/health/tap-actions'
    | '/health/water'
    | '/projects/$projectId'
    | '/goals'
    | '/health'
    | '/health/journal/$entryId'
    | '/health/journal'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bee'
    | '/_app/health'
    | '/_app/hive'
    | '/_app/jobs'
    | '/_app/mind'
    | '/_app/settings'
    | '/_app/sites'
    | '/_app/voice'
    | '/tap/$publicId'
    | '/_app/goals/$goalId'
    | '/_app/health/tap-actions'
    | '/_app/health/water'
    | '/_app/projects/$projectId'
    | '/_app/goals/'
    | '/_app/health/'
    | '/_app/health/journal/$entryId'
    | '/_app/health/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  TapPublicIdRoute: typeof TapPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap/$publicId': {
      id: '/tap/$publicId'
      path: '/tap/$publicId'
      fullPath: '/tap/$publicId'
      preLoaderRoute: typeof TapPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mind': {
      id: '/_app/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof AppMindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hive': {
      id: '/_app/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof AppHiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bee': {
      id: '/_app/bee'
      path: '/bee'
      fullPath: '/bee'
      preLoaderRoute: typeof AppBeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health/': {
      id: '/_app/health/'
      path: '/'
      fullPath: '/health/'
      preLoaderRoute: typeof AppHealthIndexRouteImport
      parentRoute: typeof AppHealthRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health/water': {
      id: '/_app/health/water'
      path: '/water'
      fullPath: '/health/water'
      preLoaderRoute: typeof AppHealthWaterRouteImport
      parentRoute: typeof AppHealthRoute
    }
    '/_app/health/tap-actions': {
      id: '/_app/health/tap-actions'
      path: '/tap-actions'
      fullPath: '/health/tap-actions'
      preLoaderRoute: typeof AppHealthTapActionsRouteImport
      parentRoute: typeof AppHealthRoute
    }
    '/_app/goals/$goalId': {
      id: '/_app/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health/journal/': {
      id: '/_app/health/journal/'
      path: '/journal'
      fullPath: '/health/journal/'
      preLoaderRoute: typeof AppHealthJournalIndexRouteImport
      parentRoute: typeof AppHealthRoute
    }
    '/_app/health/journal/$entryId': {
      id: '/_app/health/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/health/journal/$entryId'
      preLoaderRoute: typeof AppHealthJournalEntryIdRouteImport
      parentRoute: typeof AppHealthRoute
    }
  }
}

interface AppHealthRouteChildren {
  AppHealthTapActionsRoute: typeof AppHealthTapActionsRoute
  AppHealthWaterRoute: typeof AppHealthWaterRoute
  AppHealthIndexRoute: typeof AppHealthIndexRoute
  AppHealthJournalEntryIdRoute: typeof AppHealthJournalEntryIdRoute
  AppHealthJournalIndexRoute: typeof AppHealthJournalIndexRoute
}

const AppHealthRouteChildren: AppHealthRouteChildren = {
  AppHealthTapActionsRoute: AppHealthTapActionsRoute,
  AppHealthWaterRoute: AppHealthWaterRoute,
  AppHealthIndexRoute: AppHealthIndexRoute,
  AppHealthJournalEntryIdRoute: AppHealthJournalEntryIdRoute,
  AppHealthJournalIndexRoute: AppHealthJournalIndexRoute,
}

const AppHealthRouteWithChildren = AppHealthRoute._addFileChildren(
  AppHealthRouteChildren,
)

interface AppRouteChildren {
  AppBeeRoute: typeof AppBeeRoute
  AppHealthRoute: typeof AppHealthRouteWithChildren
  AppHiveRoute: typeof AppHiveRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMindRoute: typeof AppMindRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeeRoute: AppBeeRoute,
  AppHealthRoute: AppHealthRouteWithChildren,
  AppHiveRoute: AppHiveRoute,
  AppJobsRoute: AppJobsRoute,
  AppMindRoute: AppMindRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSitesRoute: AppSitesRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  TapPublicIdRoute: TapPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
