/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TapPublicIdRouteImport } from './routes/tap/$publicId'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMindRouteImport } from './routes/_app/mind'
import { Route as AppHiveRouteImport } from './routes/_app/hive'
import { Route as AppBeeRouteImport } from './routes/_app/bee'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppGoalsGoalIdRouteImport } from './routes/_app/goals/$goalId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapPublicIdRoute = TapPublicIdRouteImport.update({
  id: '/tap/$publicId',
  path: '/tap/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMindRoute = AppMindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => AppRoute,
} as any)
const AppHiveRoute = AppHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AppRoute,
} as any)
const AppBeeRoute = AppBeeRouteImport.update({
  id: '/bee',
  path: '/bee',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsGoalIdRoute = AppGoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bee': typeof AppBeeRoute
  '/hive': typeof AppHiveRoute
  '/mind': typeof AppMindRoute
  '/settings': typeof AppSettingsRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/goals/': typeof AppGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bee': typeof AppBeeRoute
  '/hive': typeof AppHiveRoute
  '/mind': typeof AppMindRoute
  '/settings': typeof AppSettingsRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/goals': typeof AppGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bee': typeof AppBeeRoute
  '/_app/hive': typeof AppHiveRoute
  '/_app/mind': typeof AppMindRoute
  '/_app/settings': typeof AppSettingsRoute
  '/tap/$publicId': typeof TapPublicIdRoute
  '/_app/goals/$goalId': typeof AppGoalsGoalIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bee'
    | '/hive'
    | '/mind'
    | '/settings'
    | '/tap/$publicId'
    | '/goals/$goalId'
    | '/projects/$projectId'
    | '/goals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bee'
    | '/hive'
    | '/mind'
    | '/settings'
    | '/tap/$publicId'
    | '/goals/$goalId'
    | '/projects/$projectId'
    | '/goals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bee'
    | '/_app/hive'
    | '/_app/mind'
    | '/_app/settings'
    | '/tap/$publicId'
    | '/_app/goals/$goalId'
    | '/_app/projects/$projectId'
    | '/_app/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  TapPublicIdRoute: typeof TapPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap/$publicId': {
      id: '/tap/$publicId'
      path: '/tap/$publicId'
      fullPath: '/tap/$publicId'
      preLoaderRoute: typeof TapPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mind': {
      id: '/_app/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof AppMindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hive': {
      id: '/_app/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof AppHiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bee': {
      id: '/_app/bee'
      path: '/bee'
      fullPath: '/bee'
      preLoaderRoute: typeof AppBeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/$goalId': {
      id: '/_app/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof AppGoalsGoalIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBeeRoute: typeof AppBeeRoute
  AppHiveRoute: typeof AppHiveRoute
  AppMindRoute: typeof AppMindRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppGoalsGoalIdRoute: typeof AppGoalsGoalIdRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBeeRoute: AppBeeRoute,
  AppHiveRoute: AppHiveRoute,
  AppMindRoute: AppMindRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppGoalsGoalIdRoute: AppGoalsGoalIdRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  TapPublicIdRoute: TapPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
