/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as StocksSplatRouteImport } from './routes/stocks.$'
import { Route as AeroStocksRouteImport } from './routes/aero.stocks'
import { Route as AeroStocksApiMarketRouteImport } from './routes/aero.stocks.api.market'
import { Route as AeroStocksApiSplatRouteImport } from './routes/aero.stocks.api.$'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSplatRoute = StocksSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StocksRoute,
} as any)
const AeroStocksRoute = AeroStocksRouteImport.update({
  id: '/aero/stocks',
  path: '/aero/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroStocksApiMarketRoute = AeroStocksApiMarketRouteImport.update({
  id: '/api/market',
  path: '/api/market',
  getParentRoute: () => AeroStocksRoute,
} as any)
const AeroStocksApiSplatRoute = AeroStocksApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => AeroStocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/agent': typeof AgentRoute
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/stocks/$': typeof StocksSplatRoute
  '/aero/stocks/api/$': typeof AeroStocksApiSplatRoute
  '/aero/stocks/api/market': typeof AeroStocksApiMarketRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AgentRoute
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/stocks/$': typeof StocksSplatRoute
  '/aero/stocks/api/$': typeof AeroStocksApiSplatRoute
  '/aero/stocks/api/market': typeof AeroStocksApiMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent': typeof AgentRoute
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/stocks/$': typeof StocksSplatRoute
  '/aero/stocks/api/$': typeof AeroStocksApiSplatRoute
  '/aero/stocks/api/market': typeof AeroStocksApiMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent'
    | '/stocks'
    | '/aero/stocks'
    | '/stocks/$'
    | '/aero/stocks/api/$'
    | '/aero/stocks/api/market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/stocks'
    | '/aero/stocks'
    | '/stocks/$'
    | '/aero/stocks/api/$'
    | '/aero/stocks/api/market'
  id:
    | '__root__'
    | '/agent'
    | '/stocks'
    | '/aero/stocks'
    | '/stocks/$'
    | '/aero/stocks/api/$'
    | '/aero/stocks/api/market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentRoute: typeof AgentRoute
  StocksRoute: typeof StocksRouteWithChildren
  AeroStocksRoute: typeof AeroStocksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$': {
      id: '/stocks/$'
      path: '/$'
      fullPath: '/stocks/$'
      preLoaderRoute: typeof StocksSplatRouteImport
      parentRoute: typeof StocksRoute
    }
    '/aero/stocks': {
      id: '/aero/stocks'
      path: '/aero/stocks'
      fullPath: '/aero/stocks'
      preLoaderRoute: typeof AeroStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aero/stocks/api/market': {
      id: '/aero/stocks/api/market'
      path: '/api/market'
      fullPath: '/aero/stocks/api/market'
      preLoaderRoute: typeof AeroStocksApiMarketRouteImport
      parentRoute: typeof AeroStocksRoute
    }
    '/aero/stocks/api/$': {
      id: '/aero/stocks/api/$'
      path: '/api/$'
      fullPath: '/aero/stocks/api/$'
      preLoaderRoute: typeof AeroStocksApiSplatRouteImport
      parentRoute: typeof AeroStocksRoute
    }
  }
}

interface StocksRouteChildren {
  StocksSplatRoute: typeof StocksSplatRoute
}

const StocksRouteChildren: StocksRouteChildren = {
  StocksSplatRoute: StocksSplatRoute,
}

const StocksRouteWithChildren =
  StocksRoute._addFileChildren(StocksRouteChildren)

interface AeroStocksRouteChildren {
  AeroStocksApiSplatRoute: typeof AeroStocksApiSplatRoute
  AeroStocksApiMarketRoute: typeof AeroStocksApiMarketRoute
}

const AeroStocksRouteChildren: AeroStocksRouteChildren = {
  AeroStocksApiSplatRoute: AeroStocksApiSplatRoute,
  AeroStocksApiMarketRoute: AeroStocksApiMarketRoute,
}

const AeroStocksRouteWithChildren = AeroStocksRoute._addFileChildren(
  AeroStocksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AgentRoute: AgentRoute,
  StocksRoute: StocksRouteWithChildren,
  AeroStocksRoute: AeroStocksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
