/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as ResearchesRouteImport } from './routes/researches'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ResearchesIndexRouteImport } from './routes/researches.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ResearchesCodeRouteImport } from './routes/researches.$code'
import { Route as AeroStocksRouteImport } from './routes/aero.stocks'
import { Route as StocksApiMarketRouteImport } from './routes/stocks.api.market'
import { Route as StocksApiSplatRouteImport } from './routes/stocks.api.$'
import { Route as ProfileSafeAddressRouteImport } from './routes/profile.safe.$address'
import { Route as AeroStocksSplatRouteImport } from './routes/aero.stocks.$'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchesRoute = ResearchesRouteImport.update({
  id: '/researches',
  path: '/researches',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchesIndexRoute = ResearchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchesRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ResearchesCodeRoute = ResearchesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ResearchesRoute,
} as any)
const AeroStocksRoute = AeroStocksRouteImport.update({
  id: '/aero/stocks',
  path: '/aero/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksApiMarketRoute = StocksApiMarketRouteImport.update({
  id: '/api/market',
  path: '/api/market',
  getParentRoute: () => StocksRoute,
} as any)
const StocksApiSplatRoute = StocksApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => StocksRoute,
} as any)
const ProfileSafeAddressRoute = ProfileSafeAddressRouteImport.update({
  id: '/safe/$address',
  path: '/safe/$address',
  getParentRoute: () => ProfileRoute,
} as any)
const AeroStocksSplatRoute = AeroStocksSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AeroStocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/agent': typeof AgentRoute
  '/profile': typeof ProfileRouteWithChildren
  '/researches': typeof ResearchesRouteWithChildren
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/researches/$code': typeof ResearchesCodeRoute
  '/profile/': typeof ProfileIndexRoute
  '/researches/': typeof ResearchesIndexRoute
  '/aero/stocks/$': typeof AeroStocksSplatRoute
  '/profile/safe/$address': typeof ProfileSafeAddressRoute
  '/stocks/api/$': typeof StocksApiSplatRoute
  '/stocks/api/market': typeof StocksApiMarketRoute
}
export interface FileRoutesByTo {
  '/agent': typeof AgentRoute
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/researches/$code': typeof ResearchesCodeRoute
  '/profile': typeof ProfileIndexRoute
  '/researches': typeof ResearchesIndexRoute
  '/aero/stocks/$': typeof AeroStocksSplatRoute
  '/profile/safe/$address': typeof ProfileSafeAddressRoute
  '/stocks/api/$': typeof StocksApiSplatRoute
  '/stocks/api/market': typeof StocksApiMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/agent': typeof AgentRoute
  '/profile': typeof ProfileRouteWithChildren
  '/researches': typeof ResearchesRouteWithChildren
  '/stocks': typeof StocksRouteWithChildren
  '/aero/stocks': typeof AeroStocksRouteWithChildren
  '/researches/$code': typeof ResearchesCodeRoute
  '/profile/': typeof ProfileIndexRoute
  '/researches/': typeof ResearchesIndexRoute
  '/aero/stocks/$': typeof AeroStocksSplatRoute
  '/profile/safe/$address': typeof ProfileSafeAddressRoute
  '/stocks/api/$': typeof StocksApiSplatRoute
  '/stocks/api/market': typeof StocksApiMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/agent'
    | '/profile'
    | '/researches'
    | '/stocks'
    | '/aero/stocks'
    | '/researches/$code'
    | '/profile/'
    | '/researches/'
    | '/aero/stocks/$'
    | '/profile/safe/$address'
    | '/stocks/api/$'
    | '/stocks/api/market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent'
    | '/stocks'
    | '/aero/stocks'
    | '/researches/$code'
    | '/profile'
    | '/researches'
    | '/aero/stocks/$'
    | '/profile/safe/$address'
    | '/stocks/api/$'
    | '/stocks/api/market'
  id:
    | '__root__'
    | '/agent'
    | '/profile'
    | '/researches'
    | '/stocks'
    | '/aero/stocks'
    | '/researches/$code'
    | '/profile/'
    | '/researches/'
    | '/aero/stocks/$'
    | '/profile/safe/$address'
    | '/stocks/api/$'
    | '/stocks/api/market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AgentRoute: typeof AgentRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResearchesRoute: typeof ResearchesRouteWithChildren
  StocksRoute: typeof StocksRouteWithChildren
  AeroStocksRoute: typeof AeroStocksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researches': {
      id: '/researches'
      path: '/researches'
      fullPath: '/researches'
      preLoaderRoute: typeof ResearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/researches/': {
      id: '/researches/'
      path: '/'
      fullPath: '/researches/'
      preLoaderRoute: typeof ResearchesIndexRouteImport
      parentRoute: typeof ResearchesRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/researches/$code': {
      id: '/researches/$code'
      path: '/$code'
      fullPath: '/researches/$code'
      preLoaderRoute: typeof ResearchesCodeRouteImport
      parentRoute: typeof ResearchesRoute
    }
    '/aero/stocks': {
      id: '/aero/stocks'
      path: '/aero/stocks'
      fullPath: '/aero/stocks'
      preLoaderRoute: typeof AeroStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/api/market': {
      id: '/stocks/api/market'
      path: '/api/market'
      fullPath: '/stocks/api/market'
      preLoaderRoute: typeof StocksApiMarketRouteImport
      parentRoute: typeof StocksRoute
    }
    '/stocks/api/$': {
      id: '/stocks/api/$'
      path: '/api/$'
      fullPath: '/stocks/api/$'
      preLoaderRoute: typeof StocksApiSplatRouteImport
      parentRoute: typeof StocksRoute
    }
    '/profile/safe/$address': {
      id: '/profile/safe/$address'
      path: '/safe/$address'
      fullPath: '/profile/safe/$address'
      preLoaderRoute: typeof ProfileSafeAddressRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/aero/stocks/$': {
      id: '/aero/stocks/$'
      path: '/$'
      fullPath: '/aero/stocks/$'
      preLoaderRoute: typeof AeroStocksSplatRouteImport
      parentRoute: typeof AeroStocksRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileSafeAddressRoute: typeof ProfileSafeAddressRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileSafeAddressRoute: ProfileSafeAddressRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ResearchesRouteChildren {
  ResearchesCodeRoute: typeof ResearchesCodeRoute
  ResearchesIndexRoute: typeof ResearchesIndexRoute
}

const ResearchesRouteChildren: ResearchesRouteChildren = {
  ResearchesCodeRoute: ResearchesCodeRoute,
  ResearchesIndexRoute: ResearchesIndexRoute,
}

const ResearchesRouteWithChildren = ResearchesRoute._addFileChildren(
  ResearchesRouteChildren,
)

interface StocksRouteChildren {
  StocksApiSplatRoute: typeof StocksApiSplatRoute
  StocksApiMarketRoute: typeof StocksApiMarketRoute
}

const StocksRouteChildren: StocksRouteChildren = {
  StocksApiSplatRoute: StocksApiSplatRoute,
  StocksApiMarketRoute: StocksApiMarketRoute,
}

const StocksRouteWithChildren =
  StocksRoute._addFileChildren(StocksRouteChildren)

interface AeroStocksRouteChildren {
  AeroStocksSplatRoute: typeof AeroStocksSplatRoute
}

const AeroStocksRouteChildren: AeroStocksRouteChildren = {
  AeroStocksSplatRoute: AeroStocksSplatRoute,
}

const AeroStocksRouteWithChildren = AeroStocksRoute._addFileChildren(
  AeroStocksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AgentRoute: AgentRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResearchesRoute: ResearchesRouteWithChildren,
  StocksRoute: StocksRouteWithChildren,
  AeroStocksRoute: AeroStocksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
