// Generated by scripts/polymarket/generate.mjs from the pinned official OpenAPI snapshots. Do not edit.
import { z } from "zod";
import { defineEndpoint } from "./endpoint";
import * as data from "./data.generated";
import * as gamma from "./gamma.generated";
import * as clob from "./clob.generated";

export const polymarketEndpoints = {
activity: defineEndpoint({ name: "activity", origin: "https://data-api.polymarket.com", path: "/v2/activity", description: "List account activity. Keyset-paginated activity feed (trades, splits, merges,\nredeems, …) in the standard `{ data, pagination }` envelope.\n\nOrdering is `(block_timestamp, sequence_id)`, `DESC` by default or `ASC` via\n`sort_direction=ASC`; both keyset-seekable. Value sorts (`CASH`/`TOKENS`)\nhave no seek anchor and are rejected with `400` rather than silently\nre-served as page one. The cursor binds the direction it was minted under\nand the resume ADOPTS it, so a replay cannot flip the walk mid-stream.\n\nA malformed `condition` id is a `400` naming the value; a\nwell-formed one that matches nothing serves an empty `data` array, which\nis the meaningful zero-state; absence means the market is not servable,\nand only that.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("Required; the feed is user-anchored."),
"limit": z.number().int().min(1).max(100).optional().describe("Page size; default 100, max 1000, past-cap rejected."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque cursor from a prior response's `next_cursor`; binds the sort\ndirection it was minted under."),
"type": z.string().min(1).max(2000).optional().describe("Activity type(s), comma-separated (TRADE, SPLIT, MERGE, REDEEM, …).\n\n`TIP` is **opt-in**: it is never in the default set, so it is only\nreturned when you name it here. A tip is a user↔user pUSD transfer that\nis not a trade-settlement leg; `size` is the amount and `side` carries the\ndirection (`IN` received / `OUT` sent)."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Condition id(s), comma-separated (at most 20 distinct values).\n`condition_id` / `conditionId` are accepted aliases."),
"event_id": z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/).optional().describe("Gamma event id(s), comma-separated (at most 20 distinct values);\nresolves to the events' markets. Mutually exclusive with `condition`."),
"side": z.enum(["BUY","SELL"]).optional().describe("BUY or SELL."),
"start": z.number().int().min(0).optional().describe("Window start on `block_timestamp`, epoch seconds (inclusive). Omitted\nor `0` floors to three years back; pass `start=1` for full history."),
"end": z.number().int().min(0).optional().describe("Window end, epoch seconds (inclusive); omitted or `0` means now plus\none day."),
"sort_by": z.literal("TIMESTAMP").optional().describe("Only `TIMESTAMP` is supported (v2 pages by keyset)."),
"sort_direction": z.enum(["ASC","DESC"]).optional().describe("`ASC` or `DESC` (default). The keyset seeks in the chosen direction;\nthe minted cursor binds it, so pass it consistently when paging."),
"exclude_deposits_withdrawals": z.boolean().optional().describe("Defaults to `true`."),
}), response: data.activityResponse, pagination: "cursor" }),
activity_combos: defineEndpoint({ name: "activity_combos", origin: "https://data-api.polymarket.com", path: "/v2/activity/combos", description: "List combo activity. Keyset-paginated combo lifecycle + redemption\nfeed for a user, in the standard `{ data, pagination }` envelope.\n\nPass `?cursor=` from a prior response's `next_cursor` to fetch the next page.\nUnlike the activity feed, the anchor behind the cursor is\n`(block_number, log_index)`; this endpoint's total order.\n\nA malformed `condition` combo condition id is a `400` naming the value; a\nwell-formed one that matches nothing serves an empty `data` array, which\nis the meaningful zero-state.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("Required; the feed is user-anchored."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Combo condition id(s), comma-separated (at most 20 distinct values).\n`condition_id` / `conditionId` are accepted aliases."),
}), response: data.activity_combosResponse, pagination: "cursor" }),
approvals: defineEndpoint({ name: "approvals", origin: "https://data-api.polymarket.com", path: "/v2/approvals", description: "Get wallet approvals. Polygon token/operator approval state for one wallet.\n\n`?user=` must be an EVM address. The complete served catalog is returned in\ncanonical order under `{ data }`; this endpoint is not paginated.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The proxy wallet whose approval state to return. Required EVM address."),
}), response: data.approvalsResponse, pagination: undefined }),
biggest_winners: defineEndpoint({ name: "biggest_winners", origin: "https://data-api.polymarket.com", path: "/v2/biggest-winners", description: "List the biggest wins. The biggest single winning positions.\n\nOne row per winning POSITION, not per user: `pnl` is\n`final_value - initial_value` for that position, and the window\n(`?time_period=`, default `day`) is on when it resolved. `?category=`\nnarrows to a market category. Deeper pages come only from `?cursor=`,\nwhich **pins the window and category it was minted on**; restating a\ndifferent one is a `400`, not a silent re-point.\n\nCombo wins are first-class rows here, tagged `kind = \"combo\"`. They carry a\n`' / '`-joined title of their legs and no Gamma event; `event_id` is `0`\nand `event_slug` empty; so **branch on `kind` before building an event\nlink**.", input: z.strictObject({
"time_period": z.enum(["day","week","month","all"]).optional().describe("Window on `resolved_at`: `day` | `week` | `month` | `all`. Defaults to `day`."),
"category": z.string().min(1).max(2000).optional().describe("`overall` (default), a Gamma market category (e.g. `sports`), or a\nsynthetic category: `combos` (combinatorial wins get their own full\ntop-500 per window) or `esports` (promoted subcategory)."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
}), response: data.biggest_winnersResponse, pagination: "cursor" }),
builders_leaderboard: defineEndpoint({ name: "builders_leaderboard", origin: "https://data-api.polymarket.com", path: "/v2/builders/leaderboard", description: "Get the builders leaderboard. The ranked board of builders by volume.\n\n`?time_period=` is `day` (default), `week`, `month` or `all` and selects the\n**window**; one row per builder in it. Deeper pages come only from\n`?cursor=`.\n\nA cursor **pins the window it was minted on**, so following it needs no\n`?time_period=`; and passing a different one is a `400` rather than a\nsilent re-point, since an offset from one board means nothing on another.\n\n`volume` is in SHARES, not USDC, the same unit as `/v2/leaderboard`'s\n`volume`. `active_users` counts distinct makers in the window.\n\n`builder` is a display name that falls back to `builder_code` for a builder\nwith no profile, so key on `builder_code` and render `builder`.", input: z.strictObject({
"time_period": z.enum(["day","week","month","all"]).optional().describe("Window: `day` | `week` | `month` | `all`. Defaults to `day`."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
}), response: data.builders_leaderboardResponse, pagination: "cursor" }),
builders_volume: defineEndpoint({ name: "builders_volume", origin: "https://data-api.polymarket.com", path: "/v2/builders/volume", description: "Get builder volume over time. The per-builder volume time series.\n\n`?interval=` is the **bucket width**, not a window: `day` (default) returns\nevery day on record bucketed daily, `week` and `month` bucket accordingly,\nand `all` buckets by calendar YEAR. `?limit=` bounds how many of the most\nrecent buckets come back (default 30); buckets, not rows, so a period is\nnever returned half-populated. `timePeriod` is accepted as an alias for\n`interval`.\n\n`rank` is the builder's placing **within its own bucket**, so it moves along\nthe series. `volume` is in SHARES; see `/v2/builders/leaderboard`.\n\nNot paginated: `data` is the array with no `pagination`, the `/v2/oi` shape.\nRows arrive newest bucket first, ranked within each.", input: z.strictObject({
"interval": z.enum(["day","week","month","all"]).optional().describe("Bucket width: `day` | `week` | `month` | `all`. Defaults to `day`.\n`timePeriod` and `time_period` are accepted aliases."),
"limit": z.number().int().min(1).max(90).optional().describe("How many of the most recent buckets to return. Defaults to 30, capped at\n90; a lower ceiling than the rest of the surface, because only ~308\ndaily buckets exist and the family maximum would return the whole series.\n\nBounds BUCKETS, not rows: a row limit would cut a bucket in half and\nleave a partial period in the series."),
}), response: data.builders_volumeResponse, pagination: undefined }),
holders: defineEndpoint({ name: "holders", origin: "https://data-api.polymarket.com", path: "/v2/holders", description: "List a market's top holders. Top holders of a market, netted per user and grouped by\noutcome token.\n\n`?condition=` (CSV of `condition_id`) is required (400 otherwise). `?limit=`\n(default 100, max 1000; v2 family-uniform) sizes the page **per outcome\ntoken**; `?min_balance=` filters the served amount.\n\n`?include_pnl=true` opts each holder row into the position economics\n(entry price and cost, current price and value, realized, unrealized and\ntotal profit) and switches the amounts to per-side gross balances, so a\nwallet holding both outcomes appears under both tokens. The default\nresponse is unchanged. This mode serves one market's table at a time:\nexactly one `condition` and `limit` at most 100 (400 otherwise, including\nvia a cursor that carries a wider window).\n\nA malformed condition id is a `400` naming the value; a well-formed one\nthat resolves to no holdings serves an empty `data` array, which is the\nmeaningful z", input: z.strictObject({
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).describe("Comma-separated `condition_id`s (at most 20 distinct values; exactly\none with `include_pnl=true`). Required. `condition` is the unified key\nacross v2 (same as the feeds and `/v2/oi`); `condition_id` /\n`conditionId` are accepted aliases."),
"limit": z.number().int().min(1).max(100).optional().describe("Rows per outcome token; defaults to 100, maximum 1000 (100 with\n`include_pnl=true`)."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`; carries\nthe per-token `(limit, offset)` window and overrides `limit`. Paging\npast the first page is cursor-only."),
"min_balance": z.number().optional().describe("Minimum net balance in shares (default 0), applied post-netting. With\n`include_pnl=true` it applies to the served per-side gross amount\ninstead."),
"include_pnl": z.boolean().optional().describe("Opt into per-holder position economics (default `false`; `includePnl`\nis an accepted alias). Adds `avg_price`, `entry_cost_usdc`,\n`current_price`, `current_value`, `realized_pnl`, `unrealized_pnl` and\n`total_pnl` to every holder row, and switches the served amounts to\nper-side gross balances: a wallet holding both outcomes appears under\nboth tokens with per-side sizes and that side's economics, matching\n`/v2/positions` for the same wallet and token. This mode serves one\nmarket's table at a time: exactly one `condition`, `limit` at most 100."),
}), response: data.holdersResponse, pagination: "cursor" }),
leaderboard: defineEndpoint({ name: "leaderboard", origin: "https://data-api.polymarket.com", path: "/v2/leaderboard", description: "Get the trader leaderboard. The ranked board of realized PnL, combos included.\n\n`?time_period=` is `day` (default), `week`, `month` or `all`; `?category=`\nis `overall` (default) or a market category; `?sort_by=` picks the `PNL`\n(default) or `VOLUME` board. Deeper pages come only from `?cursor=`.\n\nA cursor **pins the board it was minted on**; sort, window and category;\nso following it needs no params at all, and restating a different one is a\n`400` rather than a silent re-point (the builders-board pattern).\n\n`?user=` answers a different question; one wallet's standing, carrying\n**both** the PnL and volume ranks in a single object rather than a page. A\nrank of `0` there means unranked for that board, not first. `sort_by`,\n`limit` and `cursor` do not apply to that arm.\n\n**`rank` ties and skips**: tied users share a rank and the next one jumps,\nso a partition's highest rank approaches its row count. Page with the\ncurso", input: z.strictObject({
"time_period": z.enum(["day","week","month","all"]).optional().describe("Window: `day` | `week` | `month` | `all`. Defaults to `day`."),
"category": z.string().min(1).max(2000).optional().describe("`overall` (default), a Gamma market category (e.g. `sports`), or a\nsynthetic category: `combos` (combinatorial positions; PNL boards only;\nthe volume board has no combos rows) or `esports` (promoted subcategory)."),
"sort_by": z.enum(["PNL","VOLUME"]).optional().describe("Which board: `PNL` (default) or `VOLUME`."),
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional().describe("Look up one wallet's standing instead of reading the board. Returns a\nsingle object carrying both ranks, not a page."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
}), response: data.leaderboardResponse, pagination: "cursor" }),
live_volume: defineEndpoint({ name: "live_volume", origin: "https://data-api.polymarket.com", path: "/v2/live-volume", description: "Get live volume for an event. Cumulative one-side (taker) volume per market.\n\nPass `?event_id=` as a comma-separated list of integer event ids (aliases `id` / `eventId`); every market under those events is returned, `taker_volume`\ndescending, with `taker_volume_total` their sum. A list spans events. Unlike the\nfeeds this is not paginated; `data` is\nthe object with no `pagination`.\n\nUnparseable ids are ignored; a request whose ids are *all* unparseable is a\n400 rather than an empty 200, so a typo cannot read as \"no volume\". Ids are\nsorted and deduplicated before the lookup, so `?event_id=20,10` and\n`?event_id=10,20` are the same request and share a cache entry.\n\nAt most 20 distinct event ids per request, the same selector ceiling the\n`condition=` lists carry: every named event contributes all of its markets\nto a single aggregation, so the list is what sizes the request.", input: z.strictObject({
"event_id": z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/).describe("Event id(s), comma-separated (at most 20 distinct values). Required.\n`event_id` is the unified key across v2 (same as the feeds); `id` and\n`eventId` are accepted aliases."),
}), response: data.live_volumeResponse, pagination: undefined }),
oi: defineEndpoint({ name: "oi", origin: "https://data-api.polymarket.com", path: "/v2/oi", description: "Get open interest. Priced gross open interest per market.\n\nPass `?condition=` as a comma-separated list of condition ids (aliases `condition_id` / `conditionId`, matching the feeds); omit it for the single\nglobal figure (`condition_id = \"GLOBAL\"`, still a one-element array).\nEvery requested id that resolves to a servable market (indexed, active,\nnot archived; any id family) returns a row, with `value: 0` when\nnothing is held; an id absent from `data` did not resolve to a servable\nmarket. A malformed id is a `400` naming the value, so absence carries that\none meaning and nothing else. Unlike the feeds this is not paginated;\n`data` is the row array with no `pagination`.", input: z.strictObject({
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Condition id(s), comma-separated (at most 20 distinct values).\n`condition` is the unified key across v2 (same as the feeds);\n`condition_id` / `conditionId` are accepted aliases. Omit for global\nopen interest."),
}), response: data.oiResponse, pagination: undefined }),
positions: defineEndpoint({ name: "positions", origin: "https://data-api.polymarket.com", path: "/v2/positions", description: "List positions for a user or market. A keyset page of positions in the standard\n`{ data, pagination }` envelope. One route serves a user's open book, their\nclosed book (`status=CLOSED`), and a market's holders (market anchor).\n\nAt least one of `user`/`condition` is required. Supplying both anchors on the\nuser and applies `condition` as a narrowing filter.\n\n`status` defaults to `OPEN`, which is the **superset**: a\nsettled-but-unredeemed winner still holds its tokens, so it is an open\nposition whose condition resolved. `REDEEMABLE` narrows to that subset, and\neach row echoes its own `status`.\n\nResume contract: a `next_cursor` binds the `status`/`sortBy`/`sortDirection`\nthe walk started with, and following it needs nothing but `?cursor=`; the\ntoken is the authority on the spine and the total order, and the handler\nadopts all three from it. Restating them is allowed and must agree;\n**explicitly** contradicting one is a 400, bec", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional().describe("The wallet to anchor on. At least one of `user`/`condition` is required."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Condition id(s), comma-separated (at most 20 distinct values). With\n`user`, narrows that user's positions (all ids honoured). Without\n`user`, anchors on the market's holders; exactly one id is accepted\nthere, and a multi-id list is rejected rather than silently truncated."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied (the cursor's size wins)."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`. It\ncarries the page position, page size, and the status/sort/direction it\nwas minted under."),
"status": z.enum(["OPEN","REDEEMABLE","REDEEMABLE_LOST","MERGEABLE","CLOSED"]).optional().describe("One of `OPEN`, `REDEEMABLE`, `REDEEMABLE_LOST`, `MERGEABLE`, or `CLOSED`;\ndefaults to `OPEN`. `REDEEMABLE_LOST` requires `user`, supports all six\nsorts, and defaults to `CURRENT_VALUE`; it preserves row status\n`REDEEMABLE`. `MERGEABLE` is `OPEN` narrowed to live complementary pairs\n(conditions where the wallet holds >= 2 servable-live tokens) and defaults\nto `TOKENS`; it is user-scoped, so a market-anchored request renders as\n`OPEN`.\n\n`OPEN` is the superset; it includes settled-but-unredeemed winners,\nwhich `REDEEMABLE` narrows to. `CLOSED` is exited positions."),
"event_id": z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/).optional().describe("Event id(s), comma-separated (at most 20 distinct values).\nUser-anchored only."),
"title": z.string().min(1).max(2000).optional().describe("Case-insensitive market-title substring filter, honoured on every\nanchor and status. SQL LIKE wildcards (`%`, `_`) keep their usual\nmeaning; empty or whitespace-only is treated as absent; at most 200\ncharacters. NOT carried by the cursor: re-send it on every page of a\nwalk (like `condition` and the `start`/`end` window), or the cohort\nsilently widens."),
"filter_type": z.enum(["CASH","TOKENS"]).optional().describe("`CASH` or `TOKENS`; defaults to `TOKENS` (the /v2/trades-homogenized\nfilter pair, replacing the former `size_threshold`)."),
"filter_amount": z.number().optional().describe("The filter floor. `TOKENS`: minimum CURRENT holding in shares\n(defaults to the 0.1 dust floor; applies to `OPEN`/`REDEEMABLE`; a\nuser's `CLOSED` set is not narrowed by it, and on a market anchor it\nmoves the OPEN/CLOSED boundary). `CASH`: minimum mark-to-market\n`current_value` in USDC, on top of the token dust floor. Invalid\nvalues fall back to the default."),
"include_archived": z.boolean().optional().describe("Also include positions on archived markets; defaults to `false`.\n`OPEN`/`REDEEMABLE`/`REDEEMABLE_LOST`/`MERGEABLE` only; combining it with\n`status=CLOSED` is rejected. Inactive markets remain excluded either way."),
"sort_by": z.enum(["CURRENT_VALUE","PRICE","TOKENS","UNREALIZED_PNL","REALIZED_PNL","TOTAL_PNL","TIMESTAMP"]).optional().describe("One of `CURRENT_VALUE`, `PRICE`, `TOKENS`, `UNREALIZED_PNL`,\n`REALIZED_PNL`, `TOTAL_PNL`, or `TIMESTAMP` (the row's `last_event_at`).\n`PRICE` ranks by the response's effective `current_price` on every\nsupported anchor and status. On `REDEEMABLE`, the existing winners-first\npartition remains ahead of the requested price order. The default\nfollows the status: `CURRENT_VALUE` for `OPEN`/`REDEEMABLE`,\n`REALIZED_PNL` for `CLOSED`."),
"start": z.number().int().min(0).optional().describe("Inclusive lower bound on `last_event_at`, epoch seconds; omit or `0` for\nunbounded (the `/v2/activity` + `/v2/trades` vocabulary)."),
"end": z.number().int().min(0).optional().describe("Inclusive upper bound on `last_event_at`, epoch seconds; omit or `0` for\nunbounded.\n\nA position with no native economics carries no `last_event_at` and is\ntherefore **excluded by any bound**, in either direction; a window asks\nwhich positions moved inside it, and a row with no clock has no answer.\nUnbounded requests still serve those rows."),
"sort_direction": z.enum(["ASC","DESC"]).optional().describe("`ASC` or `DESC`; defaults to `DESC`."),
}), response: data.positionsResponse, pagination: "cursor" }),
positions_combos: defineEndpoint({ name: "positions_combos", origin: "https://data-api.polymarket.com", path: "/v2/positions/combos", description: "List combo positions. Combo positions for a user, in the standard\n`{ data, pagination }` envelope.\n\nSorts: `FIRST_ENTRY` (default) | `ENTRY_COST` (+ `CURRENT_VALUE` alias) |\n`UPDATED`, each with `sort_direction`. `FIRST_ENTRY DESC` pages by the\ntwo-state keyset anchor `(first_entry_at_micros, combo_condition_id,\noutcome_index)` (NULL micros = the NULL tail); `UPDATED ASC` by the\nsingle-state `(updated_at_micros, …)` anchor; every other combination by an\noffset-shaped token. The cursor binds sort + direction and the resume\nADOPTS them, so a replay cannot flip or re-sort the walk mid-stream.\n\nIt binds the cohort; `user`/`status`/`condition`/`updated_after`/\n`updated_before`; the same way: following a\npage needs nothing but `?user=` (always required here) and `?cursor=`, and\nrestating a filter is allowed but must agree. Omitting one is not a\ncontradiction, it is the absence of a choice; **contradicting** one is ", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet to anchor on. Required; combo positions are user-anchored."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied (the cursor's size wins)."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Combo condition id(s), comma-separated (at most 20 distinct values).\n`condition_id` / `conditionId` are accepted aliases."),
"status": z.string().min(1).max(2000).optional().describe("One of `OPEN`, `REDEEMABLE`, `PARTIAL`, `RESOLVED_WIN`, `RESOLVED_LOSS`,\n`RESOLVED_PARTIAL`; default (absent) is the held-visibility listing.\n\nAligned with `/v2/positions`: `OPEN` is the superset; it includes\nstill-held redeemable positions; and `REDEEMABLE` narrows to exactly\nthe rows whose `redeemable` flag is `true`. `REDEEMABLE` must be the\nsole value; the other values may be combined comma-separated and keep\nper-value equality semantics."),
"sort_by": z.string().min(1).max(2000).optional().describe("`FIRST_ENTRY` (default, except under `status=REDEEMABLE`, which defaults\nto `ENTRY_COST` so the largest claims lead) | `ENTRY_COST` |\n`CURRENT_VALUE` (alias of `ENTRY_COST`) | `UPDATED`. `FIRST_ENTRY DESC`\nand `UPDATED ASC` page by keyset; every other combination pages by an\noffset-shaped cursor. The minted cursor binds sort + direction along\nwith the `status`/`condition` cohort, so a page-2 request needs only\n`?user=` and `?cursor=`; restating a filter is allowed but must agree."),
"sort_direction": z.enum(["ASC","DESC"]).optional().describe("`ASC` or `DESC` (default `DESC`)."),
"updated_after": z.number().int().min(0).optional().describe("Incremental-sync watermark: INCLUSIVE lower bound on `updated_at`,\nepoch seconds. Without a `status` filter, either watermark serves the\nsync view; every live row (mirror-complete), not only the held\nlisting; a `status` filter keeps its own row visibility. The window's\nupper end is always capped by a short stability ceiling (about 90\nseconds behind now), so a bound in the future cannot serve rows that\nmay still move."),
"updated_before": z.number().int().min(0).optional().describe("Incremental-sync watermark: INCLUSIVE upper bound on `updated_at`,\nepoch seconds; must not precede `updated_after`. See `updated_after`\nfor the sync-view and ceiling semantics."),
}), response: data.positions_combosResponse, pagination: "cursor" }),
prices_history: defineEndpoint({ name: "prices_history", origin: "https://data-api.polymarket.com", path: "/v2/prices-history", description: "Get a token's price history. The price-history series for one outcome token, or\na single point-in-time observation.\n\nThree window forms, exactly one per request: `start` (with optional `end`),\n`interval`, or `as_of`. Points are served oldest-first; pass `?cursor=` from\na prior response's `next_cursor` for the next page.\n\n`interval=max` (or `all`) serves the market's whole life, back to 2022 for\nthe oldest markets, at 12-hour buckets unless `bucket_seconds` says\notherwise; explicit `start`/`end` windows cap at 15 days, so the presets\nare the long-range path.\n\nThe series ends with a **terminal point**: the latest observation inside the\nwindow, which is a real tick and so can fall between bucket boundaries.\nNothing may assume uniform spacing (sparse data already forbids that), and\neach point's `resolution_seconds` says what window it was observed in.\n\n**Availability is graded by resolution.** The 3-hour and 12-hour ser", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Outcome token id (the CLOB asset id the chart is keyed by). Required.\n`tokenId` is an accepted alias."),
"start": z.number().int().min(1).optional().describe("Window start, epoch seconds, INCLUSIVE. Alone it means \"up to the\npresent\", and is capped at 15 days back from now.\n\nPass `end` too when paging: a window that tracks the present keeps\ngrowing at the tip, and the 15-day cap is re-checked on every page, so a\nwalk that starts near the cap can outlive it."),
"end": z.number().int().min(1).optional().describe("Window end, epoch seconds, EXCLUSIVE. Requires `start`; on its own it\nwould ask for every point ever recorded up to `end`."),
"interval": z.enum(["max","all","1m","1w","1d","6h","1h"]).optional().describe("Relative window INSTEAD of `start`/`end`: `max`, `all`, `1m`, `1w`,\n`1d`, `6h`, `1h`, matched case-sensitively. An empty `interval=` is a\nmalformed value, not an absent one.\n\n`max`/`all` serve the market's WHOLE life (back to 2022 for the oldest\nmarkets) at 12-hour buckets by default; at `bucket_seconds` of 10800 or\n43200 the window is unbounded, while finer widths keep a 30-day window.\nThe other intervals take a width sized to their own span when\n`bucket_seconds` is omitted (`1h`/`6h`/`1d` 60, `1w` 300, `1m` 1800), and\neach still floors an explicit value: 600 for `max`/`all`/`1m`, 300 for\n`1w`."),
"bucket_seconds": z.number().int().min(60).max(86400).optional().describe("Bucket width in SECONDS (60…86400). `bucketSeconds` is an accepted alias.\n\nOMIT it and the server sizes the width to the window: the finest tier\ngrain (60, 300, 1800, 10800, 43200) that keeps the series under ~2,500\npoints, except that an explicit window wider than 12 hours never\ndefaults to the 60s grain (send `bucket_seconds=60` when you want\nsecond-by-minute detail over a longer window), and coarsened further if\nthat grain no longer reaches the window's start.\nSo a window up to 12 hours keeps 1-minute detail, half a day through a\nweek defaults to 300, fifteen days to 1800; interval presets keep their\nown span-derived defaults (`1d` 60s, `1w` 300, `1m` 1800, and the\nunbounded `max`/`all` 43200).\n\nSEND it and it is served exactly as asked, which for a window older than\nthat resolution's retention means an empty page rather than a silent\nsubstitution. An explicit value is also floored pe"),
"as_of": z.number().int().min(1).optional().describe("Point-in-time read, epoch seconds, INCLUSIVE: the latest observation at\nor before this instant. Cannot be combined with a window. `asOf` is an\naccepted alias."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size; defaults to the cap (10,000). Ignored when `cursor` is\nsupplied (the cursor's size wins)."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
}), response: data.prices_historyResponse, pagination: "cursor" }),
resolutions: defineEndpoint({ name: "resolutions", origin: "https://data-api.polymarket.com", path: "/v2/resolutions", description: "Get resolution state. Complete resolution state by one selector family.\n\nSupply exactly one of `question_id`, `condition`, or `event_id`. Condition and\nevent selectors accept comma-separated values and return condition-grain\nrows in deterministic order, preferring native V2 lifecycle, then UMA\nlifecycle, then terminal CTF state. Misses return `{ \"data\": [] }`.", input: z.strictObject({
"question_id": z.string().regex(/^0x[a-fA-F0-9]{64}$/).optional().describe("One UMA question identifier (`0x` plus 64 hexadecimal characters)."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Comma-separated Gamma condition identifiers (at most 20 distinct values)."),
"event_id": z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/).optional().describe("Comma-separated positive Gamma event IDs (at most 20 distinct values)."),
}), response: data.resolutionsResponse, pagination: undefined }),
status: defineEndpoint({ name: "status", origin: "https://data-api.polymarket.com", path: "/v2/status", description: "Get data freshness. How fresh the data behind this API is.\n\n`/readyz` answers whether this pod can reach its datastore; this answers how\nfar behind chain head what you are reading is. Two halves, because each is\nblind exactly where the other sees:\n\n* `serving`; the projections that turn ingested rows into what the feeds\n  read (`activity_feed` enrichment, `custody_balances` sync, the PnL engine).\n  Each carries its own clock, so this is the only half that can see\n  \"everything stopped\". `lag_seconds` is the worst age across them and\n  `worst` names which one, so a single stalled projection cannot hide behind\n  two healthy ones.\n* `ingestion`; one crawl cursor per `(contract, event)`, summarised as the\n  tail, the furthest-behind block, and the worst few cursors BY NAME. Every\n  reading here is relative or positional, so under a total stall it reads\n  green; that is why `serving` exists alongside it.\n\nStream", input: z.strictObject({

}), response: data.statusResponse, pagination: undefined }),
trades: defineEndpoint({ name: "trades", origin: "https://data-api.polymarket.com", path: "/v2/trades", description: "List trades. Keyset-paginated trade feed in the standard\n`{ data, pagination }` envelope.\n\nPass `?cursor=` from a prior response's `next_cursor` to fetch the next page;\nit carries both the page size and the `(block_timestamp, sequence_id)` seek\nanchor, so deep pages cost the same as shallow ones.\n\nA malformed `condition` id is a `400` naming the value; a\nwell-formed one that matches nothing serves an empty `data` array, which\nis the meaningful zero-state; absence means the market is not servable,\nand only that.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).optional().describe("Address to filter by; omit for the market/event/global feed."),
"limit": z.number().int().min(1).max(100).optional().describe("First-page size. Ignored when `cursor` is supplied (the cursor's size wins)."),
"cursor": z.string().min(1).max(16384).optional().describe("Opaque pagination cursor from a prior response's `next_cursor`."),
"taker_only": z.boolean().optional().describe("Defaults to `true`: each fill is served once, on its taker side.\n`false` includes the maker rows too."),
"filter_type": z.enum(["CASH","TOKENS"]).optional().describe("CASH or TOKENS; defaults to TOKENS."),
"filter_amount": z.number().optional().describe("Minimum trade size; defaults to 0.01, and 0 means the same."),
"start": z.number().int().min(0).optional().describe("Window start on `block_timestamp`, epoch seconds (inclusive); honored\non the `user` shape only. Omitted or `0` floors to three years back;\n`start=1` asks for full history. The `condition`/`event_id` shapes\nserve a fixed three-year window and the bare feed the rolling\ncurrent-plus-previous month, ignoring both bounds."),
"end": z.number().int().min(0).optional().describe("Window end, epoch seconds (inclusive); honored on the `user` shape\nonly; omitted or `0` means now plus one day."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Condition id(s), comma-separated (at most 20 distinct values).\n`condition_id` / `conditionId` are accepted aliases."),
"event_id": z.string().regex(/^[1-9][0-9]*(?:,[1-9][0-9]*){0,19}$/).optional().describe("Event id(s), comma-separated (at most 20 distinct values)."),
"side": z.enum(["BUY","SELL"]).optional().describe("BUY or SELL."),
}), response: data.tradesResponse, pagination: "cursor" }),
user_pnl: defineEndpoint({ name: "user_pnl", origin: "https://data-api.polymarket.com", path: "/v2/user-pnl", description: "Get a user's PnL series. Complete cumulative native-PnL atoms and compositions.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("Proxy wallet. The `user_address` spelling is accepted as an alias."),
"interval": z.enum(["max","all","1m","1w","1d","12h","6h"]).optional().describe("Window: `max`, `all`, `1m`, `1w`, `1d`, `12h`, or `6h`. Defaults to `1d`."),
"fidelity": z.enum(["1d","18h","12h","3h","1h"]).optional().describe("Output grid: `1d`, `18h`, `12h`, `3h`, or `1h`. Defaults to `1h`."),
}), response: data.user_pnlResponse, pagination: undefined }),
user_stats: defineEndpoint({ name: "user_stats", origin: "https://data-api.polymarket.com", path: "/v2/user-stats", description: "Get a user's profile stats. The profile card for one wallet in a single call.\n\n`?user=` is required. Returns `{ data: { trades, biggest_win, views,\njoin_date, all_time_pnl } }`, or `{ data: null }` when the wallet is not a\nknown user.\n\n**`data: null` and a row of zeros mean different things.** `null` is \"no such\nuser\"; zeros are \"this user exists but has never traded, never won and has no\nprofile views\".\n\n`trades` counts DISTINCT MARKETS traded, not individual trades. It is exact,\nnot estimated.\n\n`biggest_win` is the best single **resolved** position win in USDC, market\nand combo arms unified, and `0` when the wallet has no win over $1.\n\n`join_date` is epoch seconds, or `null` when unknown.\n\n`all_time_pnl` is the newest persisted cumulative `/v2/user-pnl` point at\nits actual observation timestamp. It is `null` when the user exists but no\nobservation has been published yet. For the composition card: trading\nrealized", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet whose profile stats to return. Required; `0x` followed by\n40 hexadecimal characters."),
}), response: data.user_statsResponse, pagination: undefined }),
user_volume: defineEndpoint({ name: "user_volume", origin: "https://data-api.polymarket.com", path: "/v2/user-volume", description: "Get a user's trading volume. One wallet's trading volume over a window, in both\nunits side by side.\n\n`?user=` is required. `?start=` / `?end=` are epoch seconds, inclusive and\noptional: omitted or `0` disables a bound (full history). Volume is tracked in\nwhole UTC days, so each bound is floored to its UTC day; the served window\nis the smallest whole-day window containing `[start, end]`.\n\nReturns `{ data: { volume, volume_usdc, trade_count } }`; exactly one row\nby construction (the view aggregates with no GROUP BY), zeros for a wallet\nwith no trades in the window. An inverted window is zeros too, not an error.\n\n`volume` is both-sides SHARES; `volume_usdc` is the same measure in USD;\nthe endpoint that shows the unit convention side by side: the bare name is\nthe natural unit, `_usdc` is the denomination, the same pairing as\n`current_size` / `entry_cost_usdc` on `/v2/positions`.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet whose volume to return. Required."),
"start": z.number().int().min(0).optional().describe("Window start, epoch seconds, inclusive. Omitted or `0` disables the\nbound (the feeds' convention). Volume is tracked in whole UTC days, so\nthe bound is floored to its UTC day."),
"end": z.number().int().min(0).optional().describe("Window end, epoch seconds, inclusive, floored to its UTC day. Omitted\nor `0` disables the bound."),
}), response: data.user_volumeResponse, pagination: undefined }),
value: defineEndpoint({ name: "value", origin: "https://data-api.polymarket.com", path: "/v2/value", description: "Get portfolio value. The user's portfolio value: single-market holdings marked to market plus\nunresolved combo positions at cost basis.\n\n`?user=` is required (400 otherwise). `?condition=` (CSV of `condition_id`)\nscopes the single-market term, and any condition filter excludes the\nportfolio-level combo term. `data` is a single object; a user\nwith no positions yields `{ \"data\": { \"proxy_wallet\": …, \"value\": 0 } }`.", input: z.strictObject({
"user": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet whose portfolio value to return. Required."),
"condition": z.string().regex(/^0x[a-fA-F0-9]{64}(?:,0x[a-fA-F0-9]{64}){0,19}$/).optional().describe("Comma-separated `condition_id`s (at most 20 distinct values); omit for\nthe full portfolio."),
}), response: data.valueResponse, pagination: undefined }),
search: defineEndpoint({ name: "search", origin: "https://gamma-api.polymarket.com", path: "/public-search", description: "Search markets, events, and profiles. ", input: z.strictObject({
"q": z.string().min(1).max(2000),
"events_status": z.string().min(1).max(2000).optional(),
"limit_per_type": z.number().int().min(1).max(100).optional(),
"page": z.number().int().optional(),
"events_tag": z.array(z.string().min(1).max(2000)).max(20).optional(),
"search_tags": z.boolean().optional(),
"search_profiles": z.boolean().optional(),
}), response: gamma.searchResponse, pagination: "page" }),
events: defineEndpoint({ name: "events", origin: "https://gamma-api.polymarket.com", path: "/events/keyset", description: "List events (keyset pagination). Returns events using cursor-based (keyset) pagination for stable, efficient paging through large result sets. Use `next_cursor` from each response as `after_cursor` in the next request. The `offset` parameter is explicitly rejected; use `after_cursor` instead.\n", input: z.strictObject({
"limit": z.number().int().min(1).max(100).optional().describe("Maximum number of results to return (max 100)"),
"order": z.string().min(1).max(2000).optional().describe("Comma-separated list of JSON field names to order by"),
"ascending": z.boolean().optional().describe("Sort direction. Only used when order is set."),
"after_cursor": z.string().min(1).max(16384).optional().describe("Opaque cursor token from a previous response's next_cursor"),
"slug": z.array(z.string().min(1).max(2000)).max(20).optional(),
"closed": z.boolean().optional(),
"live": z.boolean().optional(),
"title_search": z.string().min(1).max(2000).optional(),
"volume_min": z.number().optional(),
"end_date_min": z.string().min(1).max(2000).optional(),
"end_date_max": z.string().min(1).max(2000).optional(),
"tag_id": z.array(z.number().int()).max(20).optional(),
"tag_slug": z.string().min(1).max(2000).optional(),
"series_id": z.array(z.number().int()).max(20).optional(),
}), response: gamma.eventsResponse, pagination: "after_cursor" }),
markets: defineEndpoint({ name: "markets", origin: "https://gamma-api.polymarket.com", path: "/markets/keyset", description: "List markets (keyset pagination). Returns markets using cursor-based (keyset) pagination for stable, efficient paging through large result sets. Use `next_cursor` from each response as `after_cursor` in the next request. The `offset` parameter is explicitly rejected; use `after_cursor` instead.\n", input: z.strictObject({
"limit": z.number().int().min(1).max(100).optional().describe("Maximum number of results to return (max 100)"),
"order": z.string().min(1).max(2000).optional().describe("Comma-separated list of JSON field names to order by, e.g. volume_num,liquidity_num"),
"ascending": z.boolean().optional().describe("Sort direction. Only used when order is set."),
"after_cursor": z.string().min(1).max(16384).optional().describe("Opaque cursor token from a previous response's next_cursor"),
"slug": z.array(z.string().min(1).max(2000)).max(20).optional(),
"closed": z.boolean().optional(),
"clob_token_ids": z.array(z.string().min(1).max(2000)).max(20).optional(),
"condition_ids": z.array(z.string().min(1).max(2000)).max(20).optional(),
"liquidity_num_min": z.number().optional(),
"volume_num_min": z.number().optional(),
"end_date_min": z.string().min(1).max(2000).optional(),
"end_date_max": z.string().min(1).max(2000).optional(),
"tag_id": z.array(z.number().int()).max(20).optional(),
}), response: gamma.marketsResponse, pagination: "after_cursor" }),
event: defineEndpoint({ name: "event", origin: "https://gamma-api.polymarket.com", path: "/events/{id}", description: "Get event by id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
"include_chat": z.boolean().optional(),
"include_template": z.boolean().optional(),
}), response: gamma.eventResponse, pagination: undefined }),
event_by_slug: defineEndpoint({ name: "event_by_slug", origin: "https://gamma-api.polymarket.com", path: "/events/slug/{slug}", description: "Get event by slug. ", input: z.strictObject({
"slug": z.string().min(1).max(300).regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/),
"include_chat": z.boolean().optional(),
"include_template": z.boolean().optional(),
}), response: gamma.event_by_slugResponse, pagination: undefined }),
market: defineEndpoint({ name: "market", origin: "https://gamma-api.polymarket.com", path: "/markets/{id}", description: "Get market by id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
"include_tag": z.boolean().optional(),
}), response: gamma.marketResponse, pagination: undefined }),
market_by_slug: defineEndpoint({ name: "market_by_slug", origin: "https://gamma-api.polymarket.com", path: "/markets/slug/{slug}", description: "Get market by slug. ", input: z.strictObject({
"slug": z.string().min(1).max(300).regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/),
"include_tag": z.boolean().optional(),
}), response: gamma.market_by_slugResponse, pagination: undefined }),
tags: defineEndpoint({ name: "tags", origin: "https://gamma-api.polymarket.com", path: "/tags", description: "List tags. ", input: z.strictObject({
"limit": z.number().int().min(1).max(100).optional(),
"offset": z.number().int().min(0).optional(),
"order": z.string().min(1).max(2000).optional().describe("Comma-separated list of fields to order by"),
"ascending": z.boolean().optional(),
"include_template": z.boolean().optional(),
"is_carousel": z.boolean().optional(),
}), response: gamma.tagsResponse, pagination: "offset" }),
tag: defineEndpoint({ name: "tag", origin: "https://gamma-api.polymarket.com", path: "/tags/{id}", description: "Get tag by id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
"include_template": z.boolean().optional(),
}), response: gamma.tagResponse, pagination: undefined }),
tag_by_slug: defineEndpoint({ name: "tag_by_slug", origin: "https://gamma-api.polymarket.com", path: "/tags/slug/{slug}", description: "Get tag by slug. ", input: z.strictObject({
"slug": z.string().min(1).max(300).regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/),
"include_template": z.boolean().optional(),
}), response: gamma.tag_by_slugResponse, pagination: undefined }),
event_tags: defineEndpoint({ name: "event_tags", origin: "https://gamma-api.polymarket.com", path: "/events/{id}/tags", description: "Get event tags. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
}), response: gamma.event_tagsResponse, pagination: undefined }),
market_tags: defineEndpoint({ name: "market_tags", origin: "https://gamma-api.polymarket.com", path: "/markets/{id}/tags", description: "Get market tags by id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
}), response: gamma.market_tagsResponse, pagination: undefined }),
related_tags: defineEndpoint({ name: "related_tags", origin: "https://gamma-api.polymarket.com", path: "/tags/{id}/related-tags/tags", description: "Get tags related to a tag id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
"omit_empty": z.boolean().optional(),
"status": z.enum(["active","closed","all"]).optional(),
}), response: gamma.related_tagsResponse, pagination: undefined }),
series: defineEndpoint({ name: "series", origin: "https://gamma-api.polymarket.com", path: "/series", description: "List series. ", input: z.strictObject({
"limit": z.number().int().min(1).max(100).optional(),
"offset": z.number().int().min(0).optional(),
"slug": z.array(z.string().min(1).max(2000)).max(20).optional(),
"closed": z.boolean().optional(),
"recurrence": z.string().min(1).max(2000).optional(),
"exclude_events": z.boolean().optional(),
}), response: gamma.seriesResponse, pagination: "offset" }),
series_detail: defineEndpoint({ name: "series_detail", origin: "https://gamma-api.polymarket.com", path: "/series/{id}", description: "Get series by id. ", input: z.strictObject({
"id": z.string().regex(/^[0-9]+$/),
"include_chat": z.boolean().optional(),
}), response: gamma.series_detailResponse, pagination: undefined }),
sports: defineEndpoint({ name: "sports", origin: "https://gamma-api.polymarket.com", path: "/sports", description: "Get sports metadata information. ", input: z.strictObject({

}), response: gamma.sportsResponse, pagination: undefined }),
sports_market_types: defineEndpoint({ name: "sports_market_types", origin: "https://gamma-api.polymarket.com", path: "/sports/market-types", description: "Get valid sports market types. ", input: z.strictObject({

}), response: gamma.sports_market_typesResponse, pagination: undefined }),
teams: defineEndpoint({ name: "teams", origin: "https://gamma-api.polymarket.com", path: "/teams", description: "List teams. ", input: z.strictObject({
"limit": z.number().int().min(1).max(100).optional(),
"offset": z.number().int().min(0).optional(),
"order": z.string().min(1).max(2000).optional().describe("Comma-separated list of fields to order by"),
"ascending": z.boolean().optional(),
"league": z.array(z.string().min(1).max(2000)).max(20).optional(),
"name": z.array(z.string().min(1).max(2000)).max(20).optional(),
"abbreviation": z.array(z.string().min(1).max(2000)).max(20).optional(),
}), response: gamma.teamsResponse, pagination: "offset" }),
profile: defineEndpoint({ name: "profile", origin: "https://gamma-api.polymarket.com", path: "/public-profile", description: "Get public profile by wallet address. ", input: z.strictObject({
"address": z.string().regex(/^0x[a-fA-F0-9]{40}$/).describe("The wallet address (proxy wallet or user address)"),
}), response: gamma.profileResponse, pagination: undefined }),
book: defineEndpoint({ name: "book", origin: "https://clob.polymarket.com", path: "/book", description: "Get order book. Retrieves the order book summary for a specific token ID.\nIncludes bids, asks, market details, and last trade price.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.bookResponse, pagination: undefined }),
price: defineEndpoint({ name: "price", origin: "https://clob.polymarket.com", path: "/price", description: "Get market price. Retrieves the best market price for a specific token ID and side (bid or ask).\nReturns the best bid price for BUY side or best ask price for SELL side.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
"side": z.enum(["BUY","SELL"]).describe("Order side"),
}), response: clob.priceResponse, pagination: undefined }),
midpoint: defineEndpoint({ name: "midpoint", origin: "https://clob.polymarket.com", path: "/midpoint", description: "Get midpoint price. Retrieves the midpoint price for a specific token ID.\nThe midpoint is calculated as the average of the best bid and best ask prices.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.midpointResponse, pagination: undefined }),
spread: defineEndpoint({ name: "spread", origin: "https://clob.polymarket.com", path: "/spread", description: "Get spread. Retrieves the spread for a specific token ID.\nThe spread is the difference between the best ask and best bid prices.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.spreadResponse, pagination: undefined }),
last_trade_price: defineEndpoint({ name: "last_trade_price", origin: "https://clob.polymarket.com", path: "/last-trade-price", description: "Get last trade price. Retrieves the last trade price and side for a specific token ID.\nReturns default values of \"0.5\" for price and empty string for side if no trades found.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.last_trade_priceResponse, pagination: undefined }),
fee_rate: defineEndpoint({ name: "fee_rate", origin: "https://clob.polymarket.com", path: "/fee-rate", description: "Get fee rate. Retrieves the base fee rate for a specific token ID.\nThe fee rate can be provided either as a query parameter or as a path parameter.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.fee_rateResponse, pagination: undefined }),
tick_size: defineEndpoint({ name: "tick_size", origin: "https://clob.polymarket.com", path: "/tick-size", description: "Get tick size. Retrieves the minimum tick size (price increment) for a specific token ID.\nThe tick size can be provided either as a query parameter or as a path parameter.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.tick_sizeResponse, pagination: undefined }),
negative_risk: defineEndpoint({ name: "negative_risk", origin: "https://clob.polymarket.com", path: "/neg-risk", description: "Get negative risk flag. Retrieves the negative risk flag for a specific token ID.\nThe token ID can be provided either as a query parameter or as a path parameter.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("Token ID (asset ID)"),
}), response: clob.negative_riskResponse, pagination: undefined }),
clob_market: defineEndpoint({ name: "clob_market", origin: "https://clob.polymarket.com", path: "/clob-markets/{condition_id}", description: "Get CLOB market info. Returns all CLOB-level parameters for a market in a single call —\ntokens, tick size, base fees, rewards, RFQ status, and fee details.\n", input: z.strictObject({
"condition_id": z.string().regex(/^0x[a-fA-F0-9]{64}$/).describe("The condition ID of the market"),
}), response: clob.clob_marketResponse, pagination: undefined }),
market_by_token: defineEndpoint({ name: "market_by_token", origin: "https://clob.polymarket.com", path: "/markets-by-token/{token_id}", description: "Get market by token. Returns the parent market for a given token ID. Useful when you have\na token ID and need to resolve its parent market without knowing the\ncondition ID in advance.\n", input: z.strictObject({
"token_id": z.string().regex(/^(?:[0-9]+|0x[a-fA-F0-9]{64})$/).describe("The token ID to look up the parent market for"),
}), response: clob.market_by_tokenResponse, pagination: undefined }),
rewards: defineEndpoint({ name: "rewards", origin: "https://clob.polymarket.com", path: "/rewards/markets/current", description: "Get current active rewards configurations. Returns all current active rewards configurations grouped by market.\n\nWhen `sponsored=true`, returns sponsored reward configurations instead.\n\nResults are paginated (500 items per page). Use next_cursor to fetch subsequent pages.\nA next_cursor value of \"LTE=\" indicates the last page.\n", input: z.strictObject({
"sponsored": z.boolean().optional().describe("If true, returns sponsored reward configurations instead of standard ones"),
"next_cursor": z.string().min(1).max(16384).optional().describe("Pagination cursor from previous response"),
}), response: clob.rewardsResponse, pagination: "next_cursor" }),
market_rewards: defineEndpoint({ name: "market_rewards", origin: "https://clob.polymarket.com", path: "/rewards/markets/{condition_id}", description: "Get raw rewards for a specific market. Returns an array of present and future rewards configured on a market.\n\nWhen `sponsored=true`, sponsored daily rates are folded into each config's\n`rate_per_day` .\n\nResults are paginated (100 items per page). Use next_cursor to fetch subsequent pages.\nA next_cursor value of \"LTE=\" indicates the last page.\n", input: z.strictObject({
"condition_id": z.string().regex(/^0x[a-fA-F0-9]{64}$/).describe("The condition ID of the market"),
"sponsored": z.boolean().optional().describe("If true, folds sponsored daily rates into each config's rate_per_day"),
"next_cursor": z.string().min(1).max(16384).optional().describe("Pagination cursor from previous response"),
}), response: clob.market_rewardsResponse, pagination: "next_cursor" }),
server_time: defineEndpoint({ name: "server_time", origin: "https://clob.polymarket.com", path: "/time", description: "Get server time. Returns the current Unix timestamp of the server.\nThis can be used to synchronize client time with server time.\n", input: z.strictObject({

}), response: clob.server_timeResponse, pagination: undefined }),
} ;
export type PolymarketEndpointName = keyof typeof polymarketEndpoints;
export const polymarketEndpointNames = Object.keys(polymarketEndpoints).filter((name): name is PolymarketEndpointName => name in polymarketEndpoints);
