// Generated by scripts/polymarket/generate.mjs from the pinned official OpenAPI snapshots. Do not edit.
import { Schema } from "effect";

export type OrderBookSummary = {
readonly "market": string;
readonly "asset_id": string;
readonly "timestamp": string;
readonly "hash": string;
readonly "bids": ReadonlyArray<OrderSummary>;
readonly "asks": ReadonlyArray<OrderSummary>;
readonly "min_order_size": string;
readonly "tick_size": string;
readonly "neg_risk": boolean;
readonly "last_trade_price": string;
};
export const OrderBookSummary: Schema.Codec<OrderBookSummary> = Schema.suspend(() => Schema.Struct({
"market": Schema.String,
"asset_id": Schema.String,
"timestamp": Schema.String,
"hash": Schema.String,
"bids": Schema.Array(OrderSummary),
"asks": Schema.Array(OrderSummary),
"min_order_size": Schema.String,
"tick_size": Schema.String,
"neg_risk": Schema.Boolean,
"last_trade_price": Schema.String,
}));

export type OrderSummary = {
readonly "price": string;
readonly "size": string;
};
export const OrderSummary: Schema.Codec<OrderSummary> = Schema.suspend(() => Schema.Struct({
"price": Schema.String,
"size": Schema.String,
}));

export type bookResponse = OrderBookSummary;
export const bookResponse: Schema.Codec<bookResponse> = Schema.suspend(() => OrderBookSummary);

export type priceResponse = {
readonly "price": (number | string);
};
export const priceResponse: Schema.Codec<priceResponse> = Schema.suspend(() => Schema.Struct({
"price": Schema.Union([Schema.Number, Schema.String.check(Schema.isPattern(new RegExp("^(?:0|1)(?:\\.[0-9]+)?$")))]),
}));

export type midpointResponse = ({
readonly "mid": string;
} | {
readonly "mid_price": string;
});
export const midpointResponse: Schema.Codec<midpointResponse> = Schema.suspend(() => Schema.Union([Schema.Struct({
"mid": Schema.String.check(Schema.isPattern(new RegExp("^(?:0|1)(?:\\.[0-9]+)?$"))),
}), Schema.Struct({
"mid_price": Schema.String.check(Schema.isPattern(new RegExp("^(?:0|1)(?:\\.[0-9]+)?$"))),
})]));

export type spreadResponse = {
readonly "spread": string;
};
export const spreadResponse: Schema.Codec<spreadResponse> = Schema.suspend(() => Schema.Struct({
"spread": Schema.String,
}));

export type last_trade_priceResponse = {
readonly "price": string;
readonly "side": "BUY" | "SELL" | "";
};
export const last_trade_priceResponse: Schema.Codec<last_trade_priceResponse> = Schema.suspend(() => Schema.Struct({
"price": Schema.String,
"side": Schema.Literals(["BUY","SELL",""]),
}));

export type FeeRate = {
readonly "base_fee": number;
};
export const FeeRate: Schema.Codec<FeeRate> = Schema.suspend(() => Schema.Struct({
"base_fee": Schema.Number,
}));

export type fee_rateResponse = FeeRate;
export const fee_rateResponse: Schema.Codec<fee_rateResponse> = Schema.suspend(() => FeeRate);

export type TickSize = {
readonly "minimum_tick_size": number;
};
export const TickSize: Schema.Codec<TickSize> = Schema.suspend(() => Schema.Struct({
"minimum_tick_size": Schema.Number,
}));

export type tick_sizeResponse = TickSize;
export const tick_sizeResponse: Schema.Codec<tick_sizeResponse> = Schema.suspend(() => TickSize);

export type NegRisk = {
readonly "neg_risk": boolean;
};
export const NegRisk: Schema.Codec<NegRisk> = Schema.suspend(() => Schema.Struct({
"neg_risk": Schema.Boolean,
}));

export type negative_riskResponse = NegRisk;
export const negative_riskResponse: Schema.Codec<negative_riskResponse> = Schema.suspend(() => NegRisk);

export type ClobMarketDetails = {
readonly "gst"?: (string | null);
readonly "r"?: ClobRewards;
readonly "t"?: ReadonlyArray<ClobToken>;
readonly "mos"?: number;
readonly "mts"?: number;
readonly "mbf"?: number;
readonly "tbf"?: number;
readonly "rfqe"?: boolean;
readonly "itode"?: boolean;
readonly "ibce"?: boolean;
readonly "fd"?: FeeDetails;
readonly "oas"?: number;
};
export const ClobMarketDetails: Schema.Codec<ClobMarketDetails> = Schema.suspend(() => Schema.Struct({
"gst": Schema.optionalKey(Schema.NullOr(Schema.String)),
"r": Schema.optionalKey(ClobRewards),
"t": Schema.optionalKey(Schema.Array(ClobToken)),
"mos": Schema.optionalKey(Schema.Number),
"mts": Schema.optionalKey(Schema.Number),
"mbf": Schema.optionalKey(Schema.Number),
"tbf": Schema.optionalKey(Schema.Number),
"rfqe": Schema.optionalKey(Schema.Boolean),
"itode": Schema.optionalKey(Schema.Boolean),
"ibce": Schema.optionalKey(Schema.Boolean),
"fd": Schema.optionalKey(FeeDetails),
"oas": Schema.optionalKey(Schema.Number),
}));

export type ClobRewards = Readonly<Record<string, Schema.Json>>;
export const ClobRewards: Schema.Codec<ClobRewards> = Schema.suspend(() => Schema.Record(Schema.String, Schema.Json));

export type ClobToken = {
readonly "t"?: string;
readonly "o"?: string;
};
export const ClobToken: Schema.Codec<ClobToken> = Schema.suspend(() => Schema.Struct({
"t": Schema.optionalKey(Schema.String),
"o": Schema.optionalKey(Schema.String),
}));

export type FeeDetails = {
readonly "r"?: (number | null);
readonly "e"?: (number | null);
readonly "to"?: (boolean | null);
};
export const FeeDetails: Schema.Codec<FeeDetails> = Schema.suspend(() => Schema.Struct({
"r": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"e": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"to": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
}));

export type clob_marketResponse = ClobMarketDetails;
export const clob_marketResponse: Schema.Codec<clob_marketResponse> = Schema.suspend(() => ClobMarketDetails);

export type MarketByTokenResponse = {
readonly "condition_id": string;
readonly "primary_token_id": string;
readonly "secondary_token_id": string;
};
export const MarketByTokenResponse: Schema.Codec<MarketByTokenResponse> = Schema.suspend(() => Schema.Struct({
"condition_id": Schema.String,
"primary_token_id": Schema.String,
"secondary_token_id": Schema.String,
}));

export type market_by_tokenResponse = MarketByTokenResponse;
export const market_by_tokenResponse: Schema.Codec<market_by_tokenResponse> = Schema.suspend(() => MarketByTokenResponse);

export type PaginatedCurrentReward = {
readonly "limit": number;
readonly "count": number;
readonly "next_cursor": string;
readonly "data": ReadonlyArray<CurrentReward>;
};
export const PaginatedCurrentReward: Schema.Codec<PaginatedCurrentReward> = Schema.suspend(() => Schema.Struct({
"limit": Schema.Number,
"count": Schema.Number,
"next_cursor": Schema.String,
"data": Schema.Array(CurrentReward),
}));

export type CurrentReward = {
readonly "condition_id": string;
readonly "rewards_max_spread"?: number;
readonly "rewards_min_size"?: number;
readonly "rewards_config"?: ReadonlyArray<CurrentRewardConfig>;
readonly "sponsored_daily_rate"?: number;
readonly "sponsors_count"?: number;
readonly "native_daily_rate"?: number;
readonly "total_daily_rate"?: number;
};
export const CurrentReward: Schema.Codec<CurrentReward> = Schema.suspend(() => Schema.Struct({
"condition_id": Schema.String,
"rewards_max_spread": Schema.optionalKey(Schema.Number),
"rewards_min_size": Schema.optionalKey(Schema.Number),
"rewards_config": Schema.optionalKey(Schema.Array(CurrentRewardConfig)),
"sponsored_daily_rate": Schema.optionalKey(Schema.Number),
"sponsors_count": Schema.optionalKey(Schema.Number),
"native_daily_rate": Schema.optionalKey(Schema.Number),
"total_daily_rate": Schema.optionalKey(Schema.Number),
}));

export type CurrentRewardConfig = {
readonly "id"?: number;
readonly "asset_address": string;
readonly "start_date": string;
readonly "end_date"?: string;
readonly "rate_per_day": number;
readonly "total_rewards"?: number;
};
export const CurrentRewardConfig: Schema.Codec<CurrentRewardConfig> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.Number),
"asset_address": Schema.String,
"start_date": Schema.String,
"end_date": Schema.optionalKey(Schema.String),
"rate_per_day": Schema.Number,
"total_rewards": Schema.optionalKey(Schema.Number),
}));

export type rewardsResponse = PaginatedCurrentReward;
export const rewardsResponse: Schema.Codec<rewardsResponse> = Schema.suspend(() => PaginatedCurrentReward);

export type PaginatedMarketReward = {
readonly "limit": number;
readonly "count": number;
readonly "next_cursor": string;
readonly "data": ReadonlyArray<MarketReward>;
};
export const PaginatedMarketReward: Schema.Codec<PaginatedMarketReward> = Schema.suspend(() => Schema.Struct({
"limit": Schema.Number,
"count": Schema.Number,
"next_cursor": Schema.String,
"data": Schema.Array(MarketReward),
}));

export type MarketReward = {
readonly "condition_id": string;
readonly "question": string;
readonly "market_slug"?: string;
readonly "event_slug"?: string;
readonly "image"?: string;
readonly "rewards_max_spread"?: number;
readonly "rewards_min_size"?: number;
readonly "market_competitiveness"?: number;
readonly "tokens": ReadonlyArray<RewardsToken>;
readonly "rewards_config"?: ReadonlyArray<RewardsConfig>;
};
export const MarketReward: Schema.Codec<MarketReward> = Schema.suspend(() => Schema.Struct({
"condition_id": Schema.String,
"question": Schema.String,
"market_slug": Schema.optionalKey(Schema.String),
"event_slug": Schema.optionalKey(Schema.String),
"image": Schema.optionalKey(Schema.String),
"rewards_max_spread": Schema.optionalKey(Schema.Number),
"rewards_min_size": Schema.optionalKey(Schema.Number),
"market_competitiveness": Schema.optionalKey(Schema.Number),
"tokens": Schema.Array(RewardsToken),
"rewards_config": Schema.optionalKey(Schema.Array(RewardsConfig)),
}));

export type RewardsToken = {
readonly "token_id": string;
readonly "outcome": string;
readonly "price"?: number;
};
export const RewardsToken: Schema.Codec<RewardsToken> = Schema.suspend(() => Schema.Struct({
"token_id": Schema.String,
"outcome": Schema.String,
"price": Schema.optionalKey(Schema.Number),
}));

export type RewardsConfig = {
readonly "id"?: number;
readonly "asset_address": string;
readonly "start_date": string;
readonly "end_date"?: string;
readonly "rate_per_day": number;
readonly "total_rewards"?: number;
readonly "remaining_reward_amount"?: number;
readonly "total_days"?: number;
};
export const RewardsConfig: Schema.Codec<RewardsConfig> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.Number),
"asset_address": Schema.String,
"start_date": Schema.String,
"end_date": Schema.optionalKey(Schema.String),
"rate_per_day": Schema.Number,
"total_rewards": Schema.optionalKey(Schema.Number),
"remaining_reward_amount": Schema.optionalKey(Schema.Number),
"total_days": Schema.optionalKey(Schema.Number),
}));

export type market_rewardsResponse = PaginatedMarketReward;
export const market_rewardsResponse: Schema.Codec<market_rewardsResponse> = Schema.suspend(() => PaginatedMarketReward);

export type server_timeResponse = number;
export const server_timeResponse: Schema.Codec<server_timeResponse> = Schema.suspend(() => Schema.Number);
