// Generated by scripts/polymarket/generate.mjs from the pinned official OpenAPI snapshots. Do not edit.
import { Schema } from "effect";

export type ActivityPage = {
readonly "data": ReadonlyArray<Activity>;
readonly "pagination": Pagination;
};
export const ActivityPage: Schema.Codec<ActivityPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Activity),
"pagination": Pagination,
}));

export type Activity = {
readonly "bio": string;
readonly "condition_id": string;
readonly "event_slug": string;
readonly "icon": string;
readonly "is_combo"?: boolean;
readonly "name": string;
readonly "outcome": string;
readonly "outcome_index": number;
readonly "price": number;
readonly "profile_image": string;
readonly "profile_image_optimized": string;
readonly "proxy_wallet": string;
readonly "pseudonym": string;
readonly "side": string;
readonly "size": number;
readonly "slug": string;
readonly "timestamp": number;
readonly "title": string;
readonly "token_id": string;
readonly "transaction_hash": string;
readonly "type": string;
readonly "usdc_size": number;
};
export const Activity: Schema.Codec<Activity> = Schema.suspend(() => Schema.Struct({
"bio": Schema.String,
"condition_id": Schema.String,
"event_slug": Schema.String,
"icon": Schema.String,
"is_combo": Schema.optionalKey(Schema.Boolean),
"name": Schema.String,
"outcome": Schema.String,
"outcome_index": Schema.Number,
"price": Schema.Number,
"profile_image": Schema.String,
"profile_image_optimized": Schema.String,
"proxy_wallet": Schema.String,
"pseudonym": Schema.String,
"side": Schema.String,
"size": Schema.Number,
"slug": Schema.String,
"timestamp": Schema.Number,
"title": Schema.String,
"token_id": Schema.String,
"transaction_hash": Schema.String,
"type": Schema.String,
"usdc_size": Schema.Number,
}));

export type Pagination = {
readonly "has_more": boolean;
readonly "limit": number;
readonly "next_cursor"?: (string | null);
readonly "offset": number;
};
export const Pagination: Schema.Codec<Pagination> = Schema.suspend(() => Schema.Struct({
"has_more": Schema.Boolean,
"limit": Schema.Number,
"next_cursor": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"offset": Schema.Number,
}));

export type activityResponse = ActivityPage;
export const activityResponse: Schema.Codec<activityResponse> = Schema.suspend(() => ActivityPage);

export type ComboActivityPage = {
readonly "data": ReadonlyArray<ComboActivity>;
readonly "pagination": Pagination;
};
export const ComboActivityPage: Schema.Codec<ComboActivityPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(ComboActivity),
"pagination": Pagination,
}));

export type ComboActivity = {
readonly "amount_usdc"?: (number | null);
readonly "block_number": number;
readonly "combo_condition_id": string;
readonly "combo_position_id": string;
readonly "id": string;
readonly "legs": ReadonlyArray<ComboLeg>;
readonly "payout_usdc"?: (number | null);
readonly "proxy_wallet": string;
readonly "timestamp": number;
readonly "transaction_hash": string;
readonly "type": string;
};
export const ComboActivity: Schema.Codec<ComboActivity> = Schema.suspend(() => Schema.Struct({
"amount_usdc": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"block_number": Schema.Number,
"combo_condition_id": Schema.String,
"combo_position_id": Schema.String,
"id": Schema.String,
"legs": Schema.Array(ComboLeg),
"payout_usdc": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"proxy_wallet": Schema.String,
"timestamp": Schema.Number,
"transaction_hash": Schema.String,
"type": Schema.String,
}));

export type ComboLeg = {
readonly "leg_condition_id": string;
readonly "leg_current_price": number;
readonly "leg_index": number;
readonly "leg_outcome_index": number;
readonly "leg_outcome_label": string;
readonly "leg_position_id": string;
readonly "leg_resolved_at"?: (string | null);
readonly "leg_status": string;
readonly "market": ComboLegMarket;
};
export const ComboLeg: Schema.Codec<ComboLeg> = Schema.suspend(() => Schema.Struct({
"leg_condition_id": Schema.String,
"leg_current_price": Schema.Number,
"leg_index": Schema.Number,
"leg_outcome_index": Schema.Number,
"leg_outcome_label": Schema.String,
"leg_position_id": Schema.String,
"leg_resolved_at": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"leg_status": Schema.String,
"market": ComboLegMarket,
}));

export type ComboLegMarket = {
readonly "category": string;
readonly "end_date": string;
readonly "event": ComboLegEvent;
readonly "group_item_title"?: string;
readonly "icon_url": string;
readonly "image_url": string;
readonly "line"?: (number | null);
readonly "market_id": string;
readonly "outcome": string;
readonly "outcomes"?: ReadonlyArray<string>;
readonly "question"?: string;
readonly "slug": string;
readonly "sports_market_type"?: string;
readonly "subcategory": string;
readonly "tags": ReadonlyArray<string>;
readonly "title": string;
};
export const ComboLegMarket: Schema.Codec<ComboLegMarket> = Schema.suspend(() => Schema.Struct({
"category": Schema.String,
"end_date": Schema.String,
"event": ComboLegEvent,
"group_item_title": Schema.optionalKey(Schema.String),
"icon_url": Schema.String,
"image_url": Schema.String,
"line": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"market_id": Schema.String,
"outcome": Schema.String,
"outcomes": Schema.optionalKey(Schema.Array(Schema.String)),
"question": Schema.optionalKey(Schema.String),
"slug": Schema.String,
"sports_market_type": Schema.optionalKey(Schema.String),
"subcategory": Schema.String,
"tags": Schema.Array(Schema.String),
"title": Schema.String,
}));

export type ComboLegEvent = {
readonly "event_id": string;
readonly "event_image": string;
readonly "event_slug": string;
readonly "event_title": string;
};
export const ComboLegEvent: Schema.Codec<ComboLegEvent> = Schema.suspend(() => Schema.Struct({
"event_id": Schema.String,
"event_image": Schema.String,
"event_slug": Schema.String,
"event_title": Schema.String,
}));

export type activity_combosResponse = ComboActivityPage;
export const activity_combosResponse: Schema.Codec<activity_combosResponse> = Schema.suspend(() => ComboActivityPage);

export type Envelope_Approvals = {
readonly "data": {
readonly "address": string;
readonly "chain_id": number;
readonly "checked_at": string;
readonly "contracts": ReadonlyArray<ApprovalContract>;
};
};
export const Envelope_Approvals: Schema.Codec<Envelope_Approvals> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"address": Schema.String,
"chain_id": Schema.Number,
"checked_at": Schema.String,
"contracts": Schema.Array(ApprovalContract),
}),
}));

export type ApprovalContract = {
readonly "amount"?: (string | null);
readonly "approved": boolean;
readonly "feature": string;
readonly "id": string;
readonly "spender": string;
readonly "standard": string;
readonly "token": string;
};
export const ApprovalContract: Schema.Codec<ApprovalContract> = Schema.suspend(() => Schema.Struct({
"amount": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"approved": Schema.Boolean,
"feature": Schema.String,
"id": Schema.String,
"spender": Schema.String,
"standard": Schema.String,
"token": Schema.String,
}));

export type approvalsResponse = Envelope_Approvals;
export const approvalsResponse: Schema.Codec<approvalsResponse> = Schema.suspend(() => Envelope_Approvals);

export type BiggestWinnersPage = {
readonly "data": ReadonlyArray<BiggestWinner>;
readonly "pagination": Pagination;
};
export const BiggestWinnersPage: Schema.Codec<BiggestWinnersPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(BiggestWinner),
"pagination": Pagination,
}));

export type BiggestWinner = {
readonly "condition_id": string;
readonly "event_id": number;
readonly "event_slug": string;
readonly "event_title": string;
readonly "final_value": number;
readonly "initial_value": number;
readonly "kind": string;
readonly "pnl": number;
readonly "position_id": string;
readonly "profile_image": string;
readonly "resolved_at": number;
readonly "user_id": string;
readonly "user_name": string;
readonly "win_rank": number;
};
export const BiggestWinner: Schema.Codec<BiggestWinner> = Schema.suspend(() => Schema.Struct({
"condition_id": Schema.String,
"event_id": Schema.Number,
"event_slug": Schema.String,
"event_title": Schema.String,
"final_value": Schema.Number,
"initial_value": Schema.Number,
"kind": Schema.String,
"pnl": Schema.Number,
"position_id": Schema.String,
"profile_image": Schema.String,
"resolved_at": Schema.Number,
"user_id": Schema.String,
"user_name": Schema.String,
"win_rank": Schema.Number,
}));

export type biggest_winnersResponse = BiggestWinnersPage;
export const biggest_winnersResponse: Schema.Codec<biggest_winnersResponse> = Schema.suspend(() => BiggestWinnersPage);

export type BuildersLeaderboardPage = {
readonly "data": ReadonlyArray<BuilderStanding>;
readonly "pagination": Pagination;
};
export const BuildersLeaderboardPage: Schema.Codec<BuildersLeaderboardPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(BuilderStanding),
"pagination": Pagination,
}));

export type BuilderStanding = {
readonly "active_users": number;
readonly "builder_code": string;
readonly "builder_name": string;
readonly "profile_image": string;
readonly "rank": number;
readonly "verified": boolean;
readonly "volume": number;
};
export const BuilderStanding: Schema.Codec<BuilderStanding> = Schema.suspend(() => Schema.Struct({
"active_users": Schema.Number,
"builder_code": Schema.String,
"builder_name": Schema.String,
"profile_image": Schema.String,
"rank": Schema.Number,
"verified": Schema.Boolean,
"volume": Schema.Number,
}));

export type builders_leaderboardResponse = BuildersLeaderboardPage;
export const builders_leaderboardResponse: Schema.Codec<builders_leaderboardResponse> = Schema.suspend(() => BuildersLeaderboardPage);

export type Envelope_Vec_BuilderVolumePoint = {
readonly "data": ReadonlyArray<{
readonly "active_users": number;
readonly "builder_code": string;
readonly "builder_name": string;
readonly "date": string;
readonly "profile_image": string;
readonly "rank": number;
readonly "verified": boolean;
readonly "volume": number;
}>;
};
export const Envelope_Vec_BuilderVolumePoint: Schema.Codec<Envelope_Vec_BuilderVolumePoint> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Schema.Struct({
"active_users": Schema.Number,
"builder_code": Schema.String,
"builder_name": Schema.String,
"date": Schema.String,
"profile_image": Schema.String,
"rank": Schema.Number,
"verified": Schema.Boolean,
"volume": Schema.Number,
})),
}));

export type builders_volumeResponse = Envelope_Vec_BuilderVolumePoint;
export const builders_volumeResponse: Schema.Codec<builders_volumeResponse> = Schema.suspend(() => Envelope_Vec_BuilderVolumePoint);

export type HoldersPage = {
readonly "data": ReadonlyArray<MetaHolder>;
readonly "pagination": Pagination;
};
export const HoldersPage: Schema.Codec<HoldersPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(MetaHolder),
"pagination": Pagination,
}));

export type MetaHolder = {
readonly "holders": ReadonlyArray<Holder>;
readonly "token_id": string;
};
export const MetaHolder: Schema.Codec<MetaHolder> = Schema.suspend(() => Schema.Struct({
"holders": Schema.Array(Holder),
"token_id": Schema.String,
}));

export type Holder = {
readonly "amount": number;
readonly "avg_price"?: (number | null);
readonly "bio": string;
readonly "current_price"?: (number | null);
readonly "current_value"?: (number | null);
readonly "display_username_public": boolean;
readonly "entry_cost_usdc"?: (number | null);
readonly "name": string;
readonly "outcome_index": number;
readonly "profile_image": string;
readonly "profile_image_optimized": string;
readonly "proxy_wallet": string;
readonly "pseudonym": string;
readonly "realized_pnl"?: (number | null);
readonly "token_id": string;
readonly "total_pnl"?: (number | null);
readonly "unrealized_pnl"?: (number | null);
readonly "verified": boolean;
};
export const Holder: Schema.Codec<Holder> = Schema.suspend(() => Schema.Struct({
"amount": Schema.Number,
"avg_price": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"bio": Schema.String,
"current_price": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"current_value": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"display_username_public": Schema.Boolean,
"entry_cost_usdc": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"name": Schema.String,
"outcome_index": Schema.Number,
"profile_image": Schema.String,
"profile_image_optimized": Schema.String,
"proxy_wallet": Schema.String,
"pseudonym": Schema.String,
"realized_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"token_id": Schema.String,
"total_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"unrealized_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"verified": Schema.Boolean,
}));

export type holdersResponse = HoldersPage;
export const holdersResponse: Schema.Codec<holdersResponse> = Schema.suspend(() => HoldersPage);

export type LeaderboardResponse = (LeaderboardPage | Envelope_Option_LeaderboardUserEntry);
export const LeaderboardResponse: Schema.Codec<LeaderboardResponse> = Schema.suspend(() => Schema.Union([LeaderboardPage, Envelope_Option_LeaderboardUserEntry]));

export type LeaderboardPage = {
readonly "data": ReadonlyArray<LeaderboardEntry>;
readonly "pagination": Pagination;
};
export const LeaderboardPage: Schema.Codec<LeaderboardPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(LeaderboardEntry),
"pagination": Pagination,
}));

export type LeaderboardEntry = {
readonly "pnl": number;
readonly "profile_image": string;
readonly "rank": number;
readonly "user_id": string;
readonly "user_name": string;
readonly "verified": boolean;
readonly "volume": number;
readonly "x_username": string;
};
export const LeaderboardEntry: Schema.Codec<LeaderboardEntry> = Schema.suspend(() => Schema.Struct({
"pnl": Schema.Number,
"profile_image": Schema.String,
"rank": Schema.Number,
"user_id": Schema.String,
"user_name": Schema.String,
"verified": Schema.Boolean,
"volume": Schema.Number,
"x_username": Schema.String,
}));

export type Envelope_Option_LeaderboardUserEntry = {
readonly "data": (null | {
readonly "pnl": number;
readonly "profile_image": string;
readonly "rank_pnl"?: (number | null);
readonly "rank_volume"?: (number | null);
readonly "user_id": string;
readonly "user_name": string;
readonly "verified": boolean;
readonly "volume": number;
readonly "x_username": string;
});
};
export const Envelope_Option_LeaderboardUserEntry: Schema.Codec<Envelope_Option_LeaderboardUserEntry> = Schema.suspend(() => Schema.Struct({
"data": Schema.Union([Schema.Null, Schema.Struct({
"pnl": Schema.Number,
"profile_image": Schema.String,
"rank_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"rank_volume": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"user_id": Schema.String,
"user_name": Schema.String,
"verified": Schema.Boolean,
"volume": Schema.Number,
"x_username": Schema.String,
})]),
}));

export type leaderboardResponse = LeaderboardResponse;
export const leaderboardResponse: Schema.Codec<leaderboardResponse> = Schema.suspend(() => LeaderboardResponse);

export type Envelope_LiveVolume = {
readonly "data": {
readonly "conditions": ReadonlyArray<ConditionVolume>;
readonly "taker_volume_total": number;
};
};
export const Envelope_LiveVolume: Schema.Codec<Envelope_LiveVolume> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"conditions": Schema.Array(ConditionVolume),
"taker_volume_total": Schema.Number,
}),
}));

export type ConditionVolume = {
readonly "condition_id": string;
readonly "taker_volume": number;
};
export const ConditionVolume: Schema.Codec<ConditionVolume> = Schema.suspend(() => Schema.Struct({
"condition_id": Schema.String,
"taker_volume": Schema.Number,
}));

export type live_volumeResponse = Envelope_LiveVolume;
export const live_volumeResponse: Schema.Codec<live_volumeResponse> = Schema.suspend(() => Envelope_LiveVolume);

export type Envelope_Vec_OpenInterest = {
readonly "data": ReadonlyArray<{
readonly "condition_id": string;
readonly "value": number;
}>;
};
export const Envelope_Vec_OpenInterest: Schema.Codec<Envelope_Vec_OpenInterest> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Schema.Struct({
"condition_id": Schema.String,
"value": Schema.Number,
})),
}));

export type oiResponse = Envelope_Vec_OpenInterest;
export const oiResponse: Schema.Codec<oiResponse> = Schema.suspend(() => Envelope_Vec_OpenInterest);

export type PositionsPage = {
readonly "data": ReadonlyArray<Position>;
readonly "pagination": Pagination;
};
export const PositionsPage: Schema.Codec<PositionsPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Position),
"pagination": Pagination,
}));

export type Position = {
readonly "archived": boolean;
readonly "avg_price": number;
readonly "condition_id": string;
readonly "current_price": number;
readonly "current_size": number;
readonly "current_value": number;
readonly "end_date": string;
readonly "entry_cost_usdc": number;
readonly "entry_fees_usdc": number;
readonly "event_id": string;
readonly "event_slug": string;
readonly "icon": string;
readonly "last_event_at": number;
readonly "mergeable": boolean;
readonly "name": string;
readonly "negative_risk": boolean;
readonly "opposite_outcome": string;
readonly "opposite_token_id": string;
readonly "outcome": string;
readonly "outcome_index": number;
readonly "percent_pnl": number;
readonly "percent_realized_pnl": number;
readonly "profile_image": string;
readonly "proxy_wallet": string;
readonly "realized_pnl": number;
readonly "redeemable": boolean;
readonly "slug": string;
readonly "status": string;
readonly "title": string;
readonly "token_id": string;
readonly "total_cost_usdc": number;
readonly "total_pnl": number;
readonly "total_size": number;
readonly "unrealized_pnl": number;
readonly "verified": boolean;
};
export const Position: Schema.Codec<Position> = Schema.suspend(() => Schema.Struct({
"archived": Schema.Boolean,
"avg_price": Schema.Number,
"condition_id": Schema.String,
"current_price": Schema.Number,
"current_size": Schema.Number,
"current_value": Schema.Number,
"end_date": Schema.String,
"entry_cost_usdc": Schema.Number,
"entry_fees_usdc": Schema.Number,
"event_id": Schema.String,
"event_slug": Schema.String,
"icon": Schema.String,
"last_event_at": Schema.Number,
"mergeable": Schema.Boolean,
"name": Schema.String,
"negative_risk": Schema.Boolean,
"opposite_outcome": Schema.String,
"opposite_token_id": Schema.String,
"outcome": Schema.String,
"outcome_index": Schema.Number,
"percent_pnl": Schema.Number,
"percent_realized_pnl": Schema.Number,
"profile_image": Schema.String,
"proxy_wallet": Schema.String,
"realized_pnl": Schema.Number,
"redeemable": Schema.Boolean,
"slug": Schema.String,
"status": Schema.String,
"title": Schema.String,
"token_id": Schema.String,
"total_cost_usdc": Schema.Number,
"total_pnl": Schema.Number,
"total_size": Schema.Number,
"unrealized_pnl": Schema.Number,
"verified": Schema.Boolean,
}));

export type positionsResponse = PositionsPage;
export const positionsResponse: Schema.Codec<positionsResponse> = Schema.suspend(() => PositionsPage);

export type ComboPositionsPage = {
readonly "data": ReadonlyArray<ComboPosition>;
readonly "pagination": Pagination;
};
export const ComboPositionsPage: Schema.Codec<ComboPositionsPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(ComboPosition),
"pagination": Pagination,
}));

export type ComboPosition = {
readonly "combo_condition_id": string;
readonly "combo_position_id": string;
readonly "current_size": number;
readonly "entry_avg_price_usdc": number;
readonly "entry_cost_usdc": number;
readonly "entry_fees_usdc": number;
readonly "first_entry_at": string;
readonly "first_entry_at_micros"?: (number | null);
readonly "gross_entry_cost_usdc": number;
readonly "legs": ReadonlyArray<ComboLeg>;
readonly "legs_pending": number;
readonly "legs_resolved": number;
readonly "legs_total": number;
readonly "outcome_index": number;
readonly "outcome_label": string;
readonly "proxy_wallet": string;
readonly "realized_payout_usdc": number;
readonly "redeemable": boolean;
readonly "resolved_at"?: (string | null);
readonly "status": string;
readonly "updated_at": string;
readonly "updated_at_micros": number;
};
export const ComboPosition: Schema.Codec<ComboPosition> = Schema.suspend(() => Schema.Struct({
"combo_condition_id": Schema.String,
"combo_position_id": Schema.String,
"current_size": Schema.Number,
"entry_avg_price_usdc": Schema.Number,
"entry_cost_usdc": Schema.Number,
"entry_fees_usdc": Schema.Number,
"first_entry_at": Schema.String,
"first_entry_at_micros": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"gross_entry_cost_usdc": Schema.Number,
"legs": Schema.Array(ComboLeg),
"legs_pending": Schema.Number,
"legs_resolved": Schema.Number,
"legs_total": Schema.Number,
"outcome_index": Schema.Number,
"outcome_label": Schema.String,
"proxy_wallet": Schema.String,
"realized_payout_usdc": Schema.Number,
"redeemable": Schema.Boolean,
"resolved_at": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"status": Schema.String,
"updated_at": Schema.String,
"updated_at_micros": Schema.Number,
}));

export type positions_combosResponse = ComboPositionsPage;
export const positions_combosResponse: Schema.Codec<positions_combosResponse> = Schema.suspend(() => ComboPositionsPage);

export type PricesHistoryPage = {
readonly "data": ReadonlyArray<PricePoint>;
readonly "pagination": Pagination;
};
export const PricesHistoryPage: Schema.Codec<PricesHistoryPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(PricePoint),
"pagination": Pagination,
}));

export type PricePoint = {
readonly "price": number;
readonly "resolution_seconds": number;
readonly "timestamp": number;
};
export const PricePoint: Schema.Codec<PricePoint> = Schema.suspend(() => Schema.Struct({
"price": Schema.Number,
"resolution_seconds": Schema.Number,
"timestamp": Schema.Number,
}));

export type prices_historyResponse = PricesHistoryPage;
export const prices_historyResponse: Schema.Codec<prices_historyResponse> = Schema.suspend(() => PricesHistoryPage);

export type Envelope_Vec_Resolution = {
readonly "data": ReadonlyArray<{
readonly "condition_id"?: (string | null);
readonly "extended_review": boolean;
readonly "last_update_timestamp": string;
readonly "log_index": string;
readonly "market_type"?: (string | null);
readonly "new_version_q": boolean;
readonly "payouts"?: (ReadonlyArray<number> | null);
readonly "price"?: (string | null);
readonly "proposed_price"?: (string | null);
readonly "question_id"?: (string | null);
readonly "reporter"?: (string | null);
readonly "reproposed_price"?: (string | null);
readonly "resolution_source"?: (string | null);
readonly "resolved_at"?: (string | null);
readonly "resolved_block"?: (number | null);
readonly "status": string;
readonly "transaction_hash": string;
readonly "was_arbitrated"?: (boolean | null);
readonly "was_disputed": boolean;
}>;
};
export const Envelope_Vec_Resolution: Schema.Codec<Envelope_Vec_Resolution> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Schema.Struct({
"condition_id": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"extended_review": Schema.Boolean,
"last_update_timestamp": Schema.String,
"log_index": Schema.String,
"market_type": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"new_version_q": Schema.Boolean,
"payouts": Schema.optionalKey(Schema.Union([Schema.Array(Schema.Number), Schema.Null])),
"price": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"proposed_price": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"question_id": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"reporter": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"reproposed_price": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"resolution_source": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"resolved_at": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
"resolved_block": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"status": Schema.String,
"transaction_hash": Schema.String,
"was_arbitrated": Schema.optionalKey(Schema.Union([Schema.Boolean, Schema.Null])),
"was_disputed": Schema.Boolean,
})),
}));

export type resolutionsResponse = Envelope_Vec_Resolution;
export const resolutionsResponse: Schema.Codec<resolutionsResponse> = Schema.suspend(() => Envelope_Vec_Resolution);

export type Envelope_ServiceStatus = {
readonly "data": {
readonly "age_seconds": number;
readonly "computed_at": string;
readonly "ingestion": IngestionFreshness;
readonly "serving": ServingFreshness;
};
};
export const Envelope_ServiceStatus: Schema.Codec<Envelope_ServiceStatus> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"age_seconds": Schema.Number,
"computed_at": Schema.String,
"ingestion": IngestionFreshness,
"serving": ServingFreshness,
}),
}));

export type IngestionFreshness = {
readonly "chain_id": number;
readonly "cursors": number;
readonly "lagging": ReadonlyArray<CursorLag>;
readonly "max_synced_block"?: (number | null);
readonly "min_synced_block"?: (number | null);
readonly "most_lagged"?: (null | CursorLag);
readonly "network"?: (string | null);
};
export const IngestionFreshness: Schema.Codec<IngestionFreshness> = Schema.suspend(() => Schema.Struct({
"chain_id": Schema.Number,
"cursors": Schema.Number,
"lagging": Schema.Array(CursorLag),
"max_synced_block": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"min_synced_block": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"most_lagged": Schema.optionalKey(Schema.Union([Schema.Null, CursorLag])),
"network": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
}));

export type CursorLag = {
readonly "behind_max": number;
readonly "block": number;
readonly "source": string;
};
export const CursorLag: Schema.Codec<CursorLag> = Schema.suspend(() => Schema.Struct({
"behind_max": Schema.Number,
"block": Schema.Number,
"source": Schema.String,
}));

export type ServingFreshness = {
readonly "lag_seconds"?: (number | null);
readonly "mechanisms": ReadonlyArray<ServingMechanism>;
readonly "worst"?: (string | null);
};
export const ServingFreshness: Schema.Codec<ServingFreshness> = Schema.suspend(() => Schema.Struct({
"lag_seconds": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"mechanisms": Schema.Array(ServingMechanism),
"worst": Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
}));

export type ServingMechanism = {
readonly "age_seconds": number;
readonly "blocks_behind"?: (number | null);
readonly "name": string;
};
export const ServingMechanism: Schema.Codec<ServingMechanism> = Schema.suspend(() => Schema.Struct({
"age_seconds": Schema.Number,
"blocks_behind": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"name": Schema.String,
}));

export type statusResponse = Envelope_ServiceStatus;
export const statusResponse: Schema.Codec<statusResponse> = Schema.suspend(() => Envelope_ServiceStatus);

export type TradesPage = {
readonly "data": ReadonlyArray<Trade>;
readonly "pagination": Pagination;
};
export const TradesPage: Schema.Codec<TradesPage> = Schema.suspend(() => Schema.Struct({
"data": Schema.Array(Trade),
"pagination": Pagination,
}));

export type Trade = {
readonly "bio": string;
readonly "condition_id": string;
readonly "event_slug": string;
readonly "icon": string;
readonly "name": string;
readonly "outcome": string;
readonly "outcome_index": number;
readonly "price": number;
readonly "profile_image": string;
readonly "profile_image_optimized": string;
readonly "proxy_wallet": string;
readonly "pseudonym": string;
readonly "side": string;
readonly "size": number;
readonly "slug": string;
readonly "timestamp": number;
readonly "title": string;
readonly "token_id": string;
readonly "transaction_hash": string;
};
export const Trade: Schema.Codec<Trade> = Schema.suspend(() => Schema.Struct({
"bio": Schema.String,
"condition_id": Schema.String,
"event_slug": Schema.String,
"icon": Schema.String,
"name": Schema.String,
"outcome": Schema.String,
"outcome_index": Schema.Number,
"price": Schema.Number,
"profile_image": Schema.String,
"profile_image_optimized": Schema.String,
"proxy_wallet": Schema.String,
"pseudonym": Schema.String,
"side": Schema.String,
"size": Schema.Number,
"slug": Schema.String,
"timestamp": Schema.Number,
"title": Schema.String,
"token_id": Schema.String,
"transaction_hash": Schema.String,
}));

export type tradesResponse = TradesPage;
export const tradesResponse: Schema.Codec<tradesResponse> = Schema.suspend(() => TradesPage);

export type Envelope_UserPnlSeries = {
readonly "data": {
readonly "fidelity": string;
readonly "interval": string;
readonly "points": ReadonlyArray<UserPnlPoint>;
readonly "proxy_wallet": string;
readonly "source_fidelity": string;
};
};
export const Envelope_UserPnlSeries: Schema.Codec<Envelope_UserPnlSeries> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"fidelity": Schema.String,
"interval": Schema.String,
"points": Schema.Array(UserPnlPoint),
"proxy_wallet": Schema.String,
"source_fidelity": Schema.String,
}),
}));

export type UserPnlPoint = {
readonly "cashflow_net"?: (number | null);
readonly "deposits"?: (number | null);
readonly "economic_pnl"?: (number | null);
readonly "fees"?: (number | null);
readonly "fees_paid"?: (number | null);
readonly "fees_refunded"?: (number | null);
readonly "maker_rebate"?: (number | null);
readonly "position_pnl"?: (number | null);
readonly "realized_combo_pnl": number;
readonly "realized_lp_pnl": number;
readonly "realized_market_pnl": number;
readonly "realized_pnl": number;
readonly "referral_income"?: (number | null);
readonly "reward_income"?: (number | null);
readonly "settled_pnl"?: (number | null);
readonly "source_block": number;
readonly "sponsored_income"?: (number | null);
readonly "taker_rebate"?: (number | null);
readonly "timestamp": number;
readonly "trade_count": number;
readonly "trade_pnl"?: (number | null);
readonly "unrealized_pnl"?: (number | null);
readonly "volume": number;
readonly "volume_usdc": number;
readonly "wallet_income"?: (number | null);
readonly "withdrawals"?: (number | null);
readonly "yield_income"?: (number | null);
};
export const UserPnlPoint: Schema.Codec<UserPnlPoint> = Schema.suspend(() => Schema.Struct({
"cashflow_net": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"deposits": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"economic_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"fees": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"fees_paid": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"fees_refunded": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"maker_rebate": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"position_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"realized_combo_pnl": Schema.Number,
"realized_lp_pnl": Schema.Number,
"realized_market_pnl": Schema.Number,
"realized_pnl": Schema.Number,
"referral_income": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"reward_income": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"settled_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"source_block": Schema.Number,
"sponsored_income": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"taker_rebate": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"timestamp": Schema.Number,
"trade_count": Schema.Number,
"trade_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"unrealized_pnl": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"volume": Schema.Number,
"volume_usdc": Schema.Number,
"wallet_income": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"withdrawals": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"yield_income": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
}));

export type user_pnlResponse = Envelope_UserPnlSeries;
export const user_pnlResponse: Schema.Codec<user_pnlResponse> = Schema.suspend(() => Envelope_UserPnlSeries);

export type Envelope_Option_UserStats = {
readonly "data": (null | {
readonly "all_time_pnl"?: (null | UserPnlPoint);
readonly "biggest_win": number;
readonly "join_date"?: (number | null);
readonly "proxy_wallet": string;
readonly "trades": number;
readonly "views": number;
});
};
export const Envelope_Option_UserStats: Schema.Codec<Envelope_Option_UserStats> = Schema.suspend(() => Schema.Struct({
"data": Schema.Union([Schema.Null, Schema.Struct({
"all_time_pnl": Schema.optionalKey(Schema.Union([Schema.Null, UserPnlPoint])),
"biggest_win": Schema.Number,
"join_date": Schema.optionalKey(Schema.Union([Schema.Number, Schema.Null])),
"proxy_wallet": Schema.String,
"trades": Schema.Number,
"views": Schema.Number,
})]),
}));

export type user_statsResponse = Envelope_Option_UserStats;
export const user_statsResponse: Schema.Codec<user_statsResponse> = Schema.suspend(() => Envelope_Option_UserStats);

export type Envelope_UserVolume = {
readonly "data": {
readonly "trade_count": number;
readonly "volume": number;
readonly "volume_usdc": number;
};
};
export const Envelope_UserVolume: Schema.Codec<Envelope_UserVolume> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"trade_count": Schema.Number,
"volume": Schema.Number,
"volume_usdc": Schema.Number,
}),
}));

export type user_volumeResponse = Envelope_UserVolume;
export const user_volumeResponse: Schema.Codec<user_volumeResponse> = Schema.suspend(() => Envelope_UserVolume);

export type Envelope_PortfolioValue = {
readonly "data": {
readonly "proxy_wallet": string;
readonly "value": number;
};
};
export const Envelope_PortfolioValue: Schema.Codec<Envelope_PortfolioValue> = Schema.suspend(() => Schema.Struct({
"data": Schema.Struct({
"proxy_wallet": Schema.String,
"value": Schema.Number,
}),
}));

export type valueResponse = Envelope_PortfolioValue;
export const valueResponse: Schema.Codec<valueResponse> = Schema.suspend(() => Envelope_PortfolioValue);
