// Generated by scripts/polymarket/generate.mjs from the pinned official OpenAPI snapshots. Do not edit.
import { Schema } from "effect";

export type Search = {
readonly "events"?: (ReadonlyArray<Event> | null);
readonly "tags"?: (ReadonlyArray<SearchTag> | null);
readonly "profiles"?: (ReadonlyArray<Profile> | null);
readonly "pagination"?: Pagination;
};
export const Search: Schema.Codec<Search> = Schema.suspend(() => Schema.Struct({
"events": Schema.optionalKey(Schema.NullOr(Schema.Array(Event))),
"tags": Schema.optionalKey(Schema.NullOr(Schema.Array(SearchTag))),
"profiles": Schema.optionalKey(Schema.NullOr(Schema.Array(Profile))),
"pagination": Schema.optionalKey(Pagination),
}));

export type Event = {
readonly "id": string;
readonly "ticker"?: (string | null);
readonly "slug"?: (string | null);
readonly "title": (string | null);
readonly "subtitle"?: (string | null);
readonly "description"?: (string | null);
readonly "resolutionSource"?: (string | null);
readonly "startDate"?: (string | null);
readonly "creationDate"?: (string | null);
readonly "endDate"?: (string | null);
readonly "image"?: (string | null);
readonly "icon"?: (string | null);
readonly "active"?: (boolean | null);
readonly "closed"?: (boolean | null);
readonly "archived"?: (boolean | null);
readonly "new"?: (boolean | null);
readonly "featured"?: (boolean | null);
readonly "restricted"?: (boolean | null);
readonly "liquidity"?: (number | null);
readonly "volume"?: (number | null);
readonly "openInterest"?: (number | null);
readonly "sortBy"?: (string | null);
readonly "category"?: (string | null);
readonly "subcategory"?: (string | null);
readonly "isTemplate"?: (boolean | null);
readonly "templateVariables"?: (string | null);
readonly "published_at"?: (string | null);
readonly "createdBy"?: (string | null);
readonly "updatedBy"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "commentsEnabled"?: (boolean | null);
readonly "competitive"?: (number | null);
readonly "volume24hr"?: (number | null);
readonly "volume1wk"?: (number | null);
readonly "volume1mo"?: (number | null);
readonly "volume1yr"?: (number | null);
readonly "featuredImage"?: (string | null);
readonly "disqusThread"?: (string | null);
readonly "parentEvent"?: (string | null);
readonly "enableOrderBook"?: (boolean | null);
readonly "liquidityClob"?: (number | null);
readonly "negRisk"?: (boolean | null);
readonly "negRiskMarketID"?: (string | null);
readonly "negRiskFeeBips"?: (number | null);
readonly "commentCount"?: (number | null);
readonly "imageOptimized"?: ImageOptimization;
readonly "iconOptimized"?: ImageOptimization;
readonly "featuredImageOptimized"?: ImageOptimization;
readonly "subEvents"?: (ReadonlyArray<string> | null);
readonly "markets"?: ReadonlyArray<Market>;
readonly "series"?: ReadonlyArray<Series>;
readonly "categories"?: ReadonlyArray<Category>;
readonly "collections"?: ReadonlyArray<Collection>;
readonly "tags"?: ReadonlyArray<Tag>;
readonly "cyom"?: (boolean | null);
readonly "closedTime"?: (string | null);
readonly "showAllOutcomes"?: (boolean | null);
readonly "showMarketImages"?: (boolean | null);
readonly "automaticallyResolved"?: (boolean | null);
readonly "enableNegRisk"?: (boolean | null);
readonly "automaticallyActive"?: (boolean | null);
readonly "eventDate"?: (string | null);
readonly "startTime"?: (string | null);
readonly "eventWeek"?: (number | null);
readonly "seriesSlug"?: (string | null);
readonly "score"?: (string | null);
readonly "elapsed"?: (string | null);
readonly "period"?: (string | null);
readonly "live"?: (boolean | null);
readonly "ended"?: (boolean | null);
readonly "finishedTimestamp"?: (string | null);
readonly "gmpChartMode"?: (string | null);
readonly "eventCreators"?: ReadonlyArray<EventCreator>;
readonly "tweetCount"?: (number | null);
readonly "chats"?: ReadonlyArray<Chat>;
readonly "featuredOrder"?: (number | null);
readonly "estimateValue"?: (boolean | null);
readonly "cantEstimate"?: (boolean | null);
readonly "estimatedValue"?: (string | null);
readonly "templates"?: ReadonlyArray<Template>;
readonly "spreadsMainLine"?: (number | null);
readonly "totalsMainLine"?: (number | null);
readonly "carouselMap"?: (string | null);
readonly "pendingDeployment"?: (boolean | null);
readonly "deploying"?: (boolean | null);
readonly "deployingTimestamp"?: (string | null);
readonly "scheduledDeploymentTimestamp"?: (string | null);
readonly "gameStatus"?: (string | null);
};
export const Event: Schema.Codec<Event> = Schema.suspend(() => Schema.Struct({
"id": Schema.String,
"ticker": Schema.optionalKey(Schema.NullOr(Schema.String)),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"title": Schema.NullOr(Schema.String),
"subtitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"description": Schema.optionalKey(Schema.NullOr(Schema.String)),
"resolutionSource": Schema.optionalKey(Schema.NullOr(Schema.String)),
"startDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"creationDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"endDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"image": Schema.optionalKey(Schema.NullOr(Schema.String)),
"icon": Schema.optionalKey(Schema.NullOr(Schema.String)),
"active": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"closed": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"archived": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"new": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"featured": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"restricted": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"liquidity": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"openInterest": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"sortBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"category": Schema.optionalKey(Schema.NullOr(Schema.String)),
"subcategory": Schema.optionalKey(Schema.NullOr(Schema.String)),
"isTemplate": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"templateVariables": Schema.optionalKey(Schema.NullOr(Schema.String)),
"published_at": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"commentsEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"competitive": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume24hr": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1wk": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1mo": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1yr": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"featuredImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"disqusThread": Schema.optionalKey(Schema.NullOr(Schema.String)),
"parentEvent": Schema.optionalKey(Schema.NullOr(Schema.String)),
"enableOrderBook": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"liquidityClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"negRisk": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"negRiskMarketID": Schema.optionalKey(Schema.NullOr(Schema.String)),
"negRiskFeeBips": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"commentCount": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"imageOptimized": Schema.optionalKey(ImageOptimization),
"iconOptimized": Schema.optionalKey(ImageOptimization),
"featuredImageOptimized": Schema.optionalKey(ImageOptimization),
"subEvents": Schema.optionalKey(Schema.NullOr(Schema.Array(Schema.String))),
"markets": Schema.optionalKey(Schema.Array(Market)),
"series": Schema.optionalKey(Schema.Array(Series)),
"categories": Schema.optionalKey(Schema.Array(Category)),
"collections": Schema.optionalKey(Schema.Array(Collection)),
"tags": Schema.optionalKey(Schema.Array(Tag)),
"cyom": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"closedTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"showAllOutcomes": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"showMarketImages": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"automaticallyResolved": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"enableNegRisk": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"automaticallyActive": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"eventDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"startTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"eventWeek": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"seriesSlug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"score": Schema.optionalKey(Schema.NullOr(Schema.String)),
"elapsed": Schema.optionalKey(Schema.NullOr(Schema.String)),
"period": Schema.optionalKey(Schema.NullOr(Schema.String)),
"live": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"ended": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"finishedTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"gmpChartMode": Schema.optionalKey(Schema.NullOr(Schema.String)),
"eventCreators": Schema.optionalKey(Schema.Array(EventCreator)),
"tweetCount": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"chats": Schema.optionalKey(Schema.Array(Chat)),
"featuredOrder": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"estimateValue": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"cantEstimate": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"estimatedValue": Schema.optionalKey(Schema.NullOr(Schema.String)),
"templates": Schema.optionalKey(Schema.Array(Template)),
"spreadsMainLine": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"totalsMainLine": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"carouselMap": Schema.optionalKey(Schema.NullOr(Schema.String)),
"pendingDeployment": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"deploying": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"deployingTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"scheduledDeploymentTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"gameStatus": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type ImageOptimization = {
readonly "id"?: string;
readonly "imageUrlSource"?: (string | null);
readonly "imageUrlOptimized"?: (string | null);
readonly "imageSizeKbSource"?: (number | null);
readonly "imageSizeKbOptimized"?: (number | null);
readonly "imageOptimizedComplete"?: (boolean | null);
readonly "imageOptimizedLastUpdated"?: (string | null);
readonly "relID"?: (number | null);
readonly "field"?: (string | null);
readonly "relname"?: (string | null);
};
export const ImageOptimization: Schema.Codec<ImageOptimization> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"imageUrlSource": Schema.optionalKey(Schema.NullOr(Schema.String)),
"imageUrlOptimized": Schema.optionalKey(Schema.NullOr(Schema.String)),
"imageSizeKbSource": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"imageSizeKbOptimized": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"imageOptimizedComplete": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"imageOptimizedLastUpdated": Schema.optionalKey(Schema.NullOr(Schema.String)),
"relID": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"field": Schema.optionalKey(Schema.NullOr(Schema.String)),
"relname": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type Market = {
readonly "id": string;
readonly "question": (string | null);
readonly "conditionId"?: string;
readonly "slug"?: (string | null);
readonly "twitterCardImage"?: (string | null);
readonly "resolutionSource"?: (string | null);
readonly "endDate"?: (string | null);
readonly "category"?: (string | null);
readonly "liquidity"?: (string | null);
readonly "sponsorName"?: (string | null);
readonly "sponsorImage"?: (string | null);
readonly "startDate"?: (string | null);
readonly "xAxisValue"?: (string | null);
readonly "yAxisValue"?: (string | null);
readonly "denominationToken"?: (string | null);
readonly "fee"?: (string | null);
readonly "image"?: (string | null);
readonly "icon"?: (string | null);
readonly "lowerBound"?: (string | null);
readonly "upperBound"?: (string | null);
readonly "description"?: (string | null);
readonly "outcomes"?: (string | null);
readonly "outcomePrices"?: (string | null);
readonly "volume"?: (string | null);
readonly "active"?: (boolean | null);
readonly "marketType"?: (string | null);
readonly "formatType"?: (string | null);
readonly "lowerBoundDate"?: (string | null);
readonly "upperBoundDate"?: (string | null);
readonly "closed"?: (boolean | null);
readonly "createdBy"?: (number | null);
readonly "updatedBy"?: (number | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "closedTime"?: (string | null);
readonly "wideFormat"?: (boolean | null);
readonly "new"?: (boolean | null);
readonly "mailchimpTag"?: (string | null);
readonly "featured"?: (boolean | null);
readonly "archived"?: (boolean | null);
readonly "resolvedBy"?: (string | null);
readonly "restricted"?: (boolean | null);
readonly "marketGroup"?: (number | null);
readonly "groupItemTitle"?: (string | null);
readonly "groupItemThreshold"?: (string | null);
readonly "questionID"?: (string | null);
readonly "umaEndDate"?: (string | null);
readonly "enableOrderBook"?: (boolean | null);
readonly "orderPriceMinTickSize"?: (number | null);
readonly "orderMinSize"?: (number | null);
readonly "umaResolutionStatus"?: (string | null);
readonly "curationOrder"?: (number | null);
readonly "volumeNum"?: (number | null);
readonly "liquidityNum"?: (number | null);
readonly "endDateIso"?: (string | null);
readonly "startDateIso"?: (string | null);
readonly "umaEndDateIso"?: (string | null);
readonly "hasReviewedDates"?: (boolean | null);
readonly "readyForCron"?: (boolean | null);
readonly "commentsEnabled"?: (boolean | null);
readonly "volume24hr"?: (number | null);
readonly "volume1wk"?: (number | null);
readonly "volume1mo"?: (number | null);
readonly "volume1yr"?: (number | null);
readonly "gameStartTime"?: (string | null);
readonly "secondsDelay"?: (number | null);
readonly "clobTokenIds"?: (string | null);
readonly "disqusThread"?: (string | null);
readonly "shortOutcomes"?: (string | null);
readonly "teamAID"?: (string | null);
readonly "teamBID"?: (string | null);
readonly "umaBond"?: (string | null);
readonly "umaReward"?: (string | null);
readonly "volume24hrClob"?: (number | null);
readonly "volume1wkClob"?: (number | null);
readonly "volume1moClob"?: (number | null);
readonly "volume1yrClob"?: (number | null);
readonly "volumeClob"?: (number | null);
readonly "liquidityClob"?: (number | null);
readonly "makerBaseFee"?: (number | null);
readonly "takerBaseFee"?: (number | null);
readonly "customLiveness"?: (number | null);
readonly "acceptingOrders"?: (boolean | null);
readonly "notificationsEnabled"?: (boolean | null);
readonly "score"?: (number | null);
readonly "imageOptimized"?: ImageOptimization;
readonly "iconOptimized"?: ImageOptimization;
readonly "events"?: ReadonlyArray<Event>;
readonly "categories"?: ReadonlyArray<Category>;
readonly "tags"?: ReadonlyArray<Tag>;
readonly "creator"?: (string | null);
readonly "ready"?: (boolean | null);
readonly "funded"?: (boolean | null);
readonly "pastSlugs"?: (string | null);
readonly "readyTimestamp"?: (string | null);
readonly "fundedTimestamp"?: (string | null);
readonly "acceptingOrdersTimestamp"?: (string | null);
readonly "competitive"?: (number | null);
readonly "rewardsMinSize"?: (number | null);
readonly "rewardsMaxSpread"?: (number | null);
readonly "spread"?: (number | null);
readonly "automaticallyResolved"?: (boolean | null);
readonly "oneDayPriceChange"?: (number | null);
readonly "oneHourPriceChange"?: (number | null);
readonly "oneWeekPriceChange"?: (number | null);
readonly "oneMonthPriceChange"?: (number | null);
readonly "oneYearPriceChange"?: (number | null);
readonly "lastTradePrice"?: (number | null);
readonly "bestBid"?: (number | null);
readonly "bestAsk"?: (number | null);
readonly "automaticallyActive"?: (boolean | null);
readonly "clearBookOnStart"?: (boolean | null);
readonly "chartColor"?: (string | null);
readonly "seriesColor"?: (string | null);
readonly "showGmpSeries"?: (boolean | null);
readonly "showGmpOutcome"?: (boolean | null);
readonly "manualActivation"?: (boolean | null);
readonly "negRiskOther"?: (boolean | null);
readonly "gameId"?: (string | null);
readonly "groupItemRange"?: (string | null);
readonly "sportsMarketType"?: (string | null);
readonly "line"?: (number | null);
readonly "umaResolutionStatuses"?: (string | null);
readonly "pendingDeployment"?: (boolean | null);
readonly "deploying"?: (boolean | null);
readonly "deployingTimestamp"?: (string | null);
readonly "scheduledDeploymentTimestamp"?: (string | null);
readonly "rfqEnabled"?: (boolean | null);
readonly "eventStartTime"?: (string | null);
readonly "feesEnabled"?: (boolean | null);
readonly "feeSchedule"?: FeeSchedule;
};
export const Market: Schema.Codec<Market> = Schema.suspend(() => Schema.Struct({
"id": Schema.String,
"question": Schema.NullOr(Schema.String),
"conditionId": Schema.optionalKey(Schema.String),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"twitterCardImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"resolutionSource": Schema.optionalKey(Schema.NullOr(Schema.String)),
"endDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"category": Schema.optionalKey(Schema.NullOr(Schema.String)),
"liquidity": Schema.optionalKey(Schema.NullOr(Schema.String)),
"sponsorName": Schema.optionalKey(Schema.NullOr(Schema.String)),
"sponsorImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"startDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"xAxisValue": Schema.optionalKey(Schema.NullOr(Schema.String)),
"yAxisValue": Schema.optionalKey(Schema.NullOr(Schema.String)),
"denominationToken": Schema.optionalKey(Schema.NullOr(Schema.String)),
"fee": Schema.optionalKey(Schema.NullOr(Schema.String)),
"image": Schema.optionalKey(Schema.NullOr(Schema.String)),
"icon": Schema.optionalKey(Schema.NullOr(Schema.String)),
"lowerBound": Schema.optionalKey(Schema.NullOr(Schema.String)),
"upperBound": Schema.optionalKey(Schema.NullOr(Schema.String)),
"description": Schema.optionalKey(Schema.NullOr(Schema.String)),
"outcomes": Schema.optionalKey(Schema.NullOr(Schema.String)),
"outcomePrices": Schema.optionalKey(Schema.NullOr(Schema.String)),
"volume": Schema.optionalKey(Schema.NullOr(Schema.String)),
"active": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"marketType": Schema.optionalKey(Schema.NullOr(Schema.String)),
"formatType": Schema.optionalKey(Schema.NullOr(Schema.String)),
"lowerBoundDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"upperBoundDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"closed": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"closedTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"wideFormat": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"new": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"mailchimpTag": Schema.optionalKey(Schema.NullOr(Schema.String)),
"featured": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"archived": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"resolvedBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"restricted": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"marketGroup": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"groupItemTitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"groupItemThreshold": Schema.optionalKey(Schema.NullOr(Schema.String)),
"questionID": Schema.optionalKey(Schema.NullOr(Schema.String)),
"umaEndDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"enableOrderBook": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"orderPriceMinTickSize": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"orderMinSize": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"umaResolutionStatus": Schema.optionalKey(Schema.NullOr(Schema.String)),
"curationOrder": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volumeNum": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"liquidityNum": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"endDateIso": Schema.optionalKey(Schema.NullOr(Schema.String)),
"startDateIso": Schema.optionalKey(Schema.NullOr(Schema.String)),
"umaEndDateIso": Schema.optionalKey(Schema.NullOr(Schema.String)),
"hasReviewedDates": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"readyForCron": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"commentsEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"volume24hr": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1wk": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1mo": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1yr": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"gameStartTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"secondsDelay": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"clobTokenIds": Schema.optionalKey(Schema.NullOr(Schema.String)),
"disqusThread": Schema.optionalKey(Schema.NullOr(Schema.String)),
"shortOutcomes": Schema.optionalKey(Schema.NullOr(Schema.String)),
"teamAID": Schema.optionalKey(Schema.NullOr(Schema.String)),
"teamBID": Schema.optionalKey(Schema.NullOr(Schema.String)),
"umaBond": Schema.optionalKey(Schema.NullOr(Schema.String)),
"umaReward": Schema.optionalKey(Schema.NullOr(Schema.String)),
"volume24hrClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1wkClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1moClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume1yrClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volumeClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"liquidityClob": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"makerBaseFee": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"takerBaseFee": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"customLiveness": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"acceptingOrders": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"notificationsEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"score": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"imageOptimized": Schema.optionalKey(ImageOptimization),
"iconOptimized": Schema.optionalKey(ImageOptimization),
"events": Schema.optionalKey(Schema.Array(Event)),
"categories": Schema.optionalKey(Schema.Array(Category)),
"tags": Schema.optionalKey(Schema.Array(Tag)),
"creator": Schema.optionalKey(Schema.NullOr(Schema.String)),
"ready": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"funded": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"pastSlugs": Schema.optionalKey(Schema.NullOr(Schema.String)),
"readyTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"fundedTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"acceptingOrdersTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"competitive": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"rewardsMinSize": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"rewardsMaxSpread": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"spread": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"automaticallyResolved": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"oneDayPriceChange": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"oneHourPriceChange": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"oneWeekPriceChange": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"oneMonthPriceChange": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"oneYearPriceChange": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"lastTradePrice": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"bestBid": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"bestAsk": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"automaticallyActive": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"clearBookOnStart": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"chartColor": Schema.optionalKey(Schema.NullOr(Schema.String)),
"seriesColor": Schema.optionalKey(Schema.NullOr(Schema.String)),
"showGmpSeries": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"showGmpOutcome": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"manualActivation": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"negRiskOther": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"gameId": Schema.optionalKey(Schema.NullOr(Schema.String)),
"groupItemRange": Schema.optionalKey(Schema.NullOr(Schema.String)),
"sportsMarketType": Schema.optionalKey(Schema.NullOr(Schema.String)),
"line": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"umaResolutionStatuses": Schema.optionalKey(Schema.NullOr(Schema.String)),
"pendingDeployment": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"deploying": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"deployingTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"scheduledDeploymentTimestamp": Schema.optionalKey(Schema.NullOr(Schema.String)),
"rfqEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"eventStartTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"feesEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"feeSchedule": Schema.optionalKey(FeeSchedule),
}));

export type Category = {
readonly "id"?: string;
readonly "label"?: (string | null);
readonly "parentCategory"?: (string | null);
readonly "slug"?: (string | null);
readonly "publishedAt"?: (string | null);
readonly "createdBy"?: (string | null);
readonly "updatedBy"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
};
export const Category: Schema.Codec<Category> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"label": Schema.optionalKey(Schema.NullOr(Schema.String)),
"parentCategory": Schema.optionalKey(Schema.NullOr(Schema.String)),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"publishedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type Tag = {
readonly "id"?: string;
readonly "label"?: (string | null);
readonly "slug"?: (string | null);
readonly "forceShow"?: (boolean | null);
readonly "publishedAt"?: (string | null);
readonly "createdBy"?: (number | null);
readonly "updatedBy"?: (number | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "forceHide"?: (boolean | null);
readonly "isCarousel"?: (boolean | null);
};
export const Tag: Schema.Codec<Tag> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"label": Schema.optionalKey(Schema.NullOr(Schema.String)),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"forceShow": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"publishedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"forceHide": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"isCarousel": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
}));

export type FeeSchedule = {
readonly "exponent"?: (number | null);
readonly "rate"?: (number | null);
readonly "takerOnly"?: (boolean | null);
readonly "rebateRate"?: (number | null);
};
export const FeeSchedule: Schema.Codec<FeeSchedule> = Schema.suspend(() => Schema.Struct({
"exponent": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"rate": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"takerOnly": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"rebateRate": Schema.optionalKey(Schema.NullOr(Schema.Number)),
}));

export type Series = {
readonly "id"?: string;
readonly "ticker"?: (string | null);
readonly "slug"?: (string | null);
readonly "title"?: (string | null);
readonly "subtitle"?: (string | null);
readonly "seriesType"?: (string | null);
readonly "recurrence"?: (string | null);
readonly "description"?: (string | null);
readonly "image"?: (string | null);
readonly "icon"?: (string | null);
readonly "layout"?: (string | null);
readonly "active"?: (boolean | null);
readonly "closed"?: (boolean | null);
readonly "archived"?: (boolean | null);
readonly "new"?: (boolean | null);
readonly "featured"?: (boolean | null);
readonly "restricted"?: (boolean | null);
readonly "isTemplate"?: (boolean | null);
readonly "templateVariables"?: (boolean | null);
readonly "publishedAt"?: (string | null);
readonly "createdBy"?: (string | null);
readonly "updatedBy"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "commentsEnabled"?: (boolean | null);
readonly "competitive"?: (string | null);
readonly "volume24hr"?: (number | null);
readonly "volume"?: (number | null);
readonly "liquidity"?: (number | null);
readonly "startDate"?: (string | null);
readonly "pythTokenID"?: (string | null);
readonly "cgAssetName"?: (string | null);
readonly "score"?: (number | null);
readonly "events"?: ReadonlyArray<Event>;
readonly "collections"?: ReadonlyArray<Collection>;
readonly "categories"?: ReadonlyArray<Category>;
readonly "tags"?: ReadonlyArray<Tag>;
readonly "commentCount"?: (number | null);
readonly "chats"?: ReadonlyArray<Chat>;
};
export const Series: Schema.Codec<Series> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"ticker": Schema.optionalKey(Schema.NullOr(Schema.String)),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"title": Schema.optionalKey(Schema.NullOr(Schema.String)),
"subtitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"seriesType": Schema.optionalKey(Schema.NullOr(Schema.String)),
"recurrence": Schema.optionalKey(Schema.NullOr(Schema.String)),
"description": Schema.optionalKey(Schema.NullOr(Schema.String)),
"image": Schema.optionalKey(Schema.NullOr(Schema.String)),
"icon": Schema.optionalKey(Schema.NullOr(Schema.String)),
"layout": Schema.optionalKey(Schema.NullOr(Schema.String)),
"active": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"closed": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"archived": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"new": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"featured": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"restricted": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"isTemplate": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"templateVariables": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"publishedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"commentsEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"competitive": Schema.optionalKey(Schema.NullOr(Schema.String)),
"volume24hr": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"volume": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"liquidity": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"startDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
"pythTokenID": Schema.optionalKey(Schema.NullOr(Schema.String)),
"cgAssetName": Schema.optionalKey(Schema.NullOr(Schema.String)),
"score": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"events": Schema.optionalKey(Schema.Array(Event)),
"collections": Schema.optionalKey(Schema.Array(Collection)),
"categories": Schema.optionalKey(Schema.Array(Category)),
"tags": Schema.optionalKey(Schema.Array(Tag)),
"commentCount": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"chats": Schema.optionalKey(Schema.Array(Chat)),
}));

export type Collection = {
readonly "id"?: string;
readonly "ticker"?: (string | null);
readonly "slug"?: (string | null);
readonly "title"?: (string | null);
readonly "subtitle"?: (string | null);
readonly "collectionType"?: (string | null);
readonly "description"?: (string | null);
readonly "tags"?: (string | null);
readonly "image"?: (string | null);
readonly "icon"?: (string | null);
readonly "headerImage"?: (string | null);
readonly "layout"?: (string | null);
readonly "active"?: (boolean | null);
readonly "closed"?: (boolean | null);
readonly "archived"?: (boolean | null);
readonly "new"?: (boolean | null);
readonly "featured"?: (boolean | null);
readonly "restricted"?: (boolean | null);
readonly "isTemplate"?: (boolean | null);
readonly "templateVariables"?: (string | null);
readonly "publishedAt"?: (string | null);
readonly "createdBy"?: (string | null);
readonly "updatedBy"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "commentsEnabled"?: (boolean | null);
readonly "imageOptimized"?: ImageOptimization;
readonly "iconOptimized"?: ImageOptimization;
readonly "headerImageOptimized"?: ImageOptimization;
};
export const Collection: Schema.Codec<Collection> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"ticker": Schema.optionalKey(Schema.NullOr(Schema.String)),
"slug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"title": Schema.optionalKey(Schema.NullOr(Schema.String)),
"subtitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"collectionType": Schema.optionalKey(Schema.NullOr(Schema.String)),
"description": Schema.optionalKey(Schema.NullOr(Schema.String)),
"tags": Schema.optionalKey(Schema.NullOr(Schema.String)),
"image": Schema.optionalKey(Schema.NullOr(Schema.String)),
"icon": Schema.optionalKey(Schema.NullOr(Schema.String)),
"headerImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"layout": Schema.optionalKey(Schema.NullOr(Schema.String)),
"active": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"closed": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"archived": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"new": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"featured": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"restricted": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"isTemplate": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"templateVariables": Schema.optionalKey(Schema.NullOr(Schema.String)),
"publishedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"commentsEnabled": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"imageOptimized": Schema.optionalKey(ImageOptimization),
"iconOptimized": Schema.optionalKey(ImageOptimization),
"headerImageOptimized": Schema.optionalKey(ImageOptimization),
}));

export type Chat = {
readonly "id"?: string;
readonly "channelId"?: (string | null);
readonly "channelName"?: (string | null);
readonly "channelImage"?: (string | null);
readonly "live"?: (boolean | null);
readonly "startTime"?: (string | null);
readonly "endTime"?: (string | null);
};
export const Chat: Schema.Codec<Chat> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"channelId": Schema.optionalKey(Schema.NullOr(Schema.String)),
"channelName": Schema.optionalKey(Schema.NullOr(Schema.String)),
"channelImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"live": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"startTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
"endTime": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type EventCreator = {
readonly "id"?: string;
readonly "creatorName"?: (string | null);
readonly "creatorHandle"?: (string | null);
readonly "creatorUrl"?: (string | null);
readonly "creatorImage"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
};
export const EventCreator: Schema.Codec<EventCreator> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"creatorName": Schema.optionalKey(Schema.NullOr(Schema.String)),
"creatorHandle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"creatorUrl": Schema.optionalKey(Schema.NullOr(Schema.String)),
"creatorImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type Template = {
readonly "id"?: string;
readonly "eventTitle"?: (string | null);
readonly "eventSlug"?: (string | null);
readonly "eventImage"?: (string | null);
readonly "marketTitle"?: (string | null);
readonly "description"?: (string | null);
readonly "resolutionSource"?: (string | null);
readonly "negRisk"?: (boolean | null);
readonly "sortBy"?: (string | null);
readonly "showMarketImages"?: (boolean | null);
readonly "seriesSlug"?: (string | null);
readonly "outcomes"?: (string | null);
};
export const Template: Schema.Codec<Template> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"eventTitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"eventSlug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"eventImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"marketTitle": Schema.optionalKey(Schema.NullOr(Schema.String)),
"description": Schema.optionalKey(Schema.NullOr(Schema.String)),
"resolutionSource": Schema.optionalKey(Schema.NullOr(Schema.String)),
"negRisk": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"sortBy": Schema.optionalKey(Schema.NullOr(Schema.String)),
"showMarketImages": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"seriesSlug": Schema.optionalKey(Schema.NullOr(Schema.String)),
"outcomes": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type SearchTag = {
readonly "id"?: string;
readonly "label"?: string;
readonly "slug"?: string;
readonly "event_count"?: number;
};
export const SearchTag: Schema.Codec<SearchTag> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"label": Schema.optionalKey(Schema.String),
"slug": Schema.optionalKey(Schema.String),
"event_count": Schema.optionalKey(Schema.Number),
}));

export type Profile = {
readonly "id"?: string;
readonly "name"?: (string | null);
readonly "user"?: (number | null);
readonly "referral"?: (string | null);
readonly "createdBy"?: (number | null);
readonly "updatedBy"?: (number | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
readonly "utmSource"?: (string | null);
readonly "utmMedium"?: (string | null);
readonly "utmCampaign"?: (string | null);
readonly "utmContent"?: (string | null);
readonly "utmTerm"?: (string | null);
readonly "walletActivated"?: (boolean | null);
readonly "pseudonym"?: (string | null);
readonly "displayUsernamePublic"?: (boolean | null);
readonly "profileImage"?: (string | null);
readonly "bio"?: (string | null);
readonly "proxyWallet"?: (string | null);
readonly "profileImageOptimized"?: ImageOptimization;
readonly "isCloseOnly"?: (boolean | null);
readonly "isCertReq"?: (boolean | null);
readonly "certReqDate"?: (string | null);
};
export const Profile: Schema.Codec<Profile> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"name": Schema.optionalKey(Schema.NullOr(Schema.String)),
"user": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"referral": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"updatedBy": Schema.optionalKey(Schema.NullOr(Schema.Number)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"utmSource": Schema.optionalKey(Schema.NullOr(Schema.String)),
"utmMedium": Schema.optionalKey(Schema.NullOr(Schema.String)),
"utmCampaign": Schema.optionalKey(Schema.NullOr(Schema.String)),
"utmContent": Schema.optionalKey(Schema.NullOr(Schema.String)),
"utmTerm": Schema.optionalKey(Schema.NullOr(Schema.String)),
"walletActivated": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"pseudonym": Schema.optionalKey(Schema.NullOr(Schema.String)),
"displayUsernamePublic": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"profileImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"bio": Schema.optionalKey(Schema.NullOr(Schema.String)),
"proxyWallet": Schema.optionalKey(Schema.NullOr(Schema.String)),
"profileImageOptimized": Schema.optionalKey(ImageOptimization),
"isCloseOnly": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"isCertReq": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"certReqDate": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type Pagination = {
readonly "hasMore"?: boolean;
readonly "totalResults"?: number;
};
export const Pagination: Schema.Codec<Pagination> = Schema.suspend(() => Schema.Struct({
"hasMore": Schema.optionalKey(Schema.Boolean),
"totalResults": Schema.optionalKey(Schema.Number),
}));

export type searchResponse = Search;
export const searchResponse: Schema.Codec<searchResponse> = Schema.suspend(() => Search);

export type KeysetEventsResponse = {
readonly "events": ReadonlyArray<Event>;
readonly "next_cursor"?: string;
};
export const KeysetEventsResponse: Schema.Codec<KeysetEventsResponse> = Schema.suspend(() => Schema.Struct({
"events": Schema.Array(Event),
"next_cursor": Schema.optionalKey(Schema.String),
}));

export type eventsResponse = KeysetEventsResponse;
export const eventsResponse: Schema.Codec<eventsResponse> = Schema.suspend(() => KeysetEventsResponse);

export type KeysetMarketsResponse = {
readonly "markets": ReadonlyArray<Market>;
readonly "next_cursor"?: string;
};
export const KeysetMarketsResponse: Schema.Codec<KeysetMarketsResponse> = Schema.suspend(() => Schema.Struct({
"markets": Schema.Array(Market),
"next_cursor": Schema.optionalKey(Schema.String),
}));

export type marketsResponse = KeysetMarketsResponse;
export const marketsResponse: Schema.Codec<marketsResponse> = Schema.suspend(() => KeysetMarketsResponse);

export type eventResponse = Event;
export const eventResponse: Schema.Codec<eventResponse> = Schema.suspend(() => Event);

export type event_by_slugResponse = Event;
export const event_by_slugResponse: Schema.Codec<event_by_slugResponse> = Schema.suspend(() => Event);

export type marketResponse = Market;
export const marketResponse: Schema.Codec<marketResponse> = Schema.suspend(() => Market);

export type market_by_slugResponse = Market;
export const market_by_slugResponse: Schema.Codec<market_by_slugResponse> = Schema.suspend(() => Market);

export type tagsResponse = ReadonlyArray<Tag>;
export const tagsResponse: Schema.Codec<tagsResponse> = Schema.suspend(() => Schema.Array(Tag));

export type tagResponse = Tag;
export const tagResponse: Schema.Codec<tagResponse> = Schema.suspend(() => Tag);

export type tag_by_slugResponse = Tag;
export const tag_by_slugResponse: Schema.Codec<tag_by_slugResponse> = Schema.suspend(() => Tag);

export type event_tagsResponse = ReadonlyArray<Tag>;
export const event_tagsResponse: Schema.Codec<event_tagsResponse> = Schema.suspend(() => Schema.Array(Tag));

export type market_tagsResponse = ReadonlyArray<Tag>;
export const market_tagsResponse: Schema.Codec<market_tagsResponse> = Schema.suspend(() => Schema.Array(Tag));

export type related_tagsResponse = ReadonlyArray<Tag>;
export const related_tagsResponse: Schema.Codec<related_tagsResponse> = Schema.suspend(() => Schema.Array(Tag));

export type seriesResponse = ReadonlyArray<Series>;
export const seriesResponse: Schema.Codec<seriesResponse> = Schema.suspend(() => Schema.Array(Series));

export type series_detailResponse = Series;
export const series_detailResponse: Schema.Codec<series_detailResponse> = Schema.suspend(() => Series);

export type SportsMetadata = {
readonly "sport"?: string;
readonly "image"?: string;
readonly "resolution"?: string;
readonly "ordering"?: string;
readonly "tags"?: string;
readonly "series"?: string;
};
export const SportsMetadata: Schema.Codec<SportsMetadata> = Schema.suspend(() => Schema.Struct({
"sport": Schema.optionalKey(Schema.String),
"image": Schema.optionalKey(Schema.String),
"resolution": Schema.optionalKey(Schema.String),
"ordering": Schema.optionalKey(Schema.String),
"tags": Schema.optionalKey(Schema.String),
"series": Schema.optionalKey(Schema.String),
}));

export type sportsResponse = ReadonlyArray<SportsMetadata>;
export const sportsResponse: Schema.Codec<sportsResponse> = Schema.suspend(() => Schema.Array(SportsMetadata));

export type SportsMarketTypesResponse = {
readonly "marketTypes"?: ReadonlyArray<string>;
};
export const SportsMarketTypesResponse: Schema.Codec<SportsMarketTypesResponse> = Schema.suspend(() => Schema.Struct({
"marketTypes": Schema.optionalKey(Schema.Array(Schema.String)),
}));

export type sports_market_typesResponse = SportsMarketTypesResponse;
export const sports_market_typesResponse: Schema.Codec<sports_market_typesResponse> = Schema.suspend(() => SportsMarketTypesResponse);

export type Team = {
readonly "id"?: number;
readonly "name"?: (string | null);
readonly "league"?: (string | null);
readonly "record"?: (string | null);
readonly "logo"?: (string | null);
readonly "abbreviation"?: (string | null);
readonly "alias"?: (string | null);
readonly "createdAt"?: (string | null);
readonly "updatedAt"?: (string | null);
};
export const Team: Schema.Codec<Team> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.Number),
"name": Schema.optionalKey(Schema.NullOr(Schema.String)),
"league": Schema.optionalKey(Schema.NullOr(Schema.String)),
"record": Schema.optionalKey(Schema.NullOr(Schema.String)),
"logo": Schema.optionalKey(Schema.NullOr(Schema.String)),
"abbreviation": Schema.optionalKey(Schema.NullOr(Schema.String)),
"alias": Schema.optionalKey(Schema.NullOr(Schema.String)),
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"updatedAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
}));

export type teamsResponse = ReadonlyArray<Team>;
export const teamsResponse: Schema.Codec<teamsResponse> = Schema.suspend(() => Schema.Array(Team));

export type PublicProfileResponse = {
readonly "createdAt"?: (string | null);
readonly "proxyWallet"?: (string | null);
readonly "profileImage"?: (string | null);
readonly "displayUsernamePublic"?: (boolean | null);
readonly "bio"?: (string | null);
readonly "pseudonym"?: (string | null);
readonly "name"?: (string | null);
readonly "users"?: (ReadonlyArray<PublicProfileUser> | null);
readonly "xUsername"?: (string | null);
readonly "verifiedBadge"?: (boolean | null);
};
export const PublicProfileResponse: Schema.Codec<PublicProfileResponse> = Schema.suspend(() => Schema.Struct({
"createdAt": Schema.optionalKey(Schema.NullOr(Schema.String)),
"proxyWallet": Schema.optionalKey(Schema.NullOr(Schema.String)),
"profileImage": Schema.optionalKey(Schema.NullOr(Schema.String)),
"displayUsernamePublic": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
"bio": Schema.optionalKey(Schema.NullOr(Schema.String)),
"pseudonym": Schema.optionalKey(Schema.NullOr(Schema.String)),
"name": Schema.optionalKey(Schema.NullOr(Schema.String)),
"users": Schema.optionalKey(Schema.NullOr(Schema.Array(PublicProfileUser))),
"xUsername": Schema.optionalKey(Schema.NullOr(Schema.String)),
"verifiedBadge": Schema.optionalKey(Schema.NullOr(Schema.Boolean)),
}));

export type PublicProfileUser = {
readonly "id"?: string;
readonly "creator"?: boolean;
readonly "mod"?: boolean;
};
export const PublicProfileUser: Schema.Codec<PublicProfileUser> = Schema.suspend(() => Schema.Struct({
"id": Schema.optionalKey(Schema.String),
"creator": Schema.optionalKey(Schema.Boolean),
"mod": Schema.optionalKey(Schema.Boolean),
}));

export type profileResponse = PublicProfileResponse;
export const profileResponse: Schema.Codec<profileResponse> = Schema.suspend(() => PublicProfileResponse);
