/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/pecu/wrangler.aero.jsonc --include-runtime=false --env-interface=AeroEnv apps/pecu/src/cloudflare/aero-env.d.ts` (hash: 81ab1cec636b2d2725c0a22b775c47e8)
interface __BaseEnv_AeroEnv {
	AERO_CATALOG: R2Bucket;
	ALCHEMY_RPC_URL: string;
	AERO_REFRESH: DurableObjectNamespace<import("./aero-entry").AeroCatalog>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./aero-entry");
		durableNamespaces: "AeroCatalog";
	}
	interface Env extends __BaseEnv_AeroEnv {}
}
interface AeroEnv extends __BaseEnv_AeroEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALCHEMY_RPC_URL">> {}
}
