import { mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(import.meta.dir, '../..');
const bottle = process.argv.includes('--bottle');
const model = Buffer.from(await Bun.file(`${root}/assets/${bottle ? 'water-3d/water-bottle' : 'hive-3d/hive'}.glb`).arrayBuffer()).toString('base64');
const fallback = Buffer.from(await Bun.file(`${root}/assets/${bottle ? 'water-3d/bottle' : 'hive-3d/hive'}-fallback.png`).arrayBuffer()).toString('base64');
const result = await Bun.build({
  entrypoints: [resolve(import.meta.dir, 'src/viewer.ts')],
  target: 'browser', format: 'iife', minify: true,
  define: { IS_BOTTLE: JSON.stringify(bottle), HIVE_GLB: JSON.stringify(model), HIVE_EMPTY: JSON.stringify(`data:image/png;base64,${fallback}`) },
});
if (!result.success) throw new AggregateError(result.logs, 'Hive viewer build failed');
const script = (await result.outputs[0]!.text()).replaceAll('</script', '<\\/script');
const license = await Bun.file(resolve(dirname(fileURLToPath(import.meta.resolve('three'))), '../LICENSE')).text();
const html = `<!doctype html><html><head><title>${bottle ? 'Water bottle' : 'Honey vessel'}</title><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'"><style>html{color-scheme:light dark}html,body,#hive{margin:0;width:100vw;height:100vh;overflow:hidden;background:transparent}#hive{position:relative;touch-action:pan-y;cursor:grab;outline-offset:-4px}#hive:active{cursor:grabbing}canvas,#fallback{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}#fallback{z-index:1;pointer-events:none}[hidden]{display:none}</style></head><body><div id="hive" role="img" tabindex="0"><img id="fallback" alt=""></div><script>${script}</script></body></html>`;
await Bun.write(resolve(import.meta.dir, bottle ? 'src/bottle-generated.ts' : 'src/generated.ts'), `// Generated by bun run --cwd packages/hive-3d build.\nexport const ${bottle ? 'BOTTLE_HTML' : 'HIVE_HTML'} = ${JSON.stringify(html)};\n`);
const android = `${root}/apps/android/app/src/main/assets/${bottle ? 'water3d' : 'hive3d'}`;
await mkdir(android, { recursive: true });
await Bun.write(`${android}/index.html`, html);
await Bun.write(`${android}/THREE-LICENSE.txt`, license);
await Bun.write(resolve(import.meta.dir, 'THREE-LICENSE.txt'), license);
console.log(`Built offline Hive viewer: ${Math.round(html.length / 1024)} KB, Android and TypeScript outputs`);
